package function.vector;

//import Functions.AFunction;
import math.vector.VectorDouble;
import math.vector.VectorFloat;

/**This Class encapsulates the the Charge Field Function,
 * resulting from the Poisson Equation, in arbitrary Dimensions.
 * Because except for a constant Factor this is the Green Function
 * for the Poisson Equastion: phi(r) = 1/r => y[i] = -y[i]/r^3
 * , it returns the Force Field Vector generated by the Point Charges.
 *
 * The given Coordinates are examples for simple MultiPoles
 * to generate MultiPole Moments: M(Order) =  Sum (c[m]*r[m]^Order) = M[i,j,k,...].
 * The linear Versions of the QuadruPole and OctoPole are simply denaturated Versions
 * of their planar counterparts.
 * To define a Multipol of higher order you need three Dimensions.
 * All Multipoles have their center of Charge in the Origin of the Coordinate System.
 * The MultiPole Moments of lesser Order are Zero with these Examples, i.e.
 * MultiPoles of Order > 0 (MonoPole) are electrically neutral etc.
 * The MultiPole Moments of higher Order are not Zero with these Examples,
 * <!-- docstate
 * pass: 2
 * mtime: 2026-09-05T10:13:18Z
 * digest: b43ede2018f0ca5e2423ce2919ecff1c2946c665525b86fc274e1940b33c10f3
 * stale: false
 * tags: [code/vector_math, code/function_composition]
 * concepts: [Vector Field Function]
 * facets: {layer: utility, status: legacy, complexity: low}
 * -->
 * because the MultiPoles have an extent!	*/
public class fChargeField
extends AFloatVectorField {

////////////////////////////////////////////////////////////////////////////
/// #region : static Constants and Variables
////////////////////////////////////////////////////////////////////////////

	/**Square Root of 1/2 = 0.7172..., needed for the Coordinates of the MultiPoles	 */
	final static public double SqRtHalf = Math.sqrt(0.5);

	/**Coordinates for a pure MonoPol, i.e. one Charge Unit
	 * in the Center of the Coordinate System	 */
	final static public double [][] MonoPol = {{0}};

	/**Coordinates for a pure DiPol along the x Axis with a Distance of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] DiPol   = {{-1}, {+1}};

	/**Coordinates for a pure planar QuadruPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] QuadPol = {
		DiPol[0], DiPol[1], {0, -1}, {0, +1}};

	/**Coordinates for a pure linear QuadruPol on in the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] lQuadPol= {
		DiPol[0], MonoPol[0], DiPol[1]};

	/**Coordinates for a pure planar OctoPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] OctoPol = {
		QuadPol[0], QuadPol[1], QuadPol[2], QuadPol[3],
		{+SqRtHalf,+SqRtHalf}, {+SqRtHalf,-SqRtHalf},
		{-SqRtHalf,+SqRtHalf}, {-SqRtHalf,-SqRtHalf}};

	/**Coordinates for a pure linear OctoPol on the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] lOctoPol= {
		DiPol [0], {-SqRtHalf}, MonoPol[0], {+SqRtHalf}, DiPol [1]};


	/**Charges for a pure MonoPol, i.e. one Charge Unit in the Center of the Coordinate System	 */
	final static public double [] cMonoPol = {1};

	/**Charges for a pure DiPol along the x Axis with a Distance of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] cDiPol	= {-1, +1};

	/**Charges for a pure linear QuadruPol on in the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] clQuadPol= {+1, -2, +1};

	/**Charges for a pure planar QuadruPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] cQuadPol = {+1, +1, -1, -1};

	/**Charges for a pure planar OctoPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] cOctoPol = {
		+1, +1, +1, +1,
		-1, -1, -1, -1};

	/**Charges for a pure linear OctoPol on the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] clOctoPol= { +1, -2, +2, -2, +1};

	////////////////////////////////////////////////////////////////////////////
	/// #region : Variables
	////////////////////////////////////////////////////////////////////////////
	
	/**Number of Charges	 */
	protected int numCharges;

	/**Positions of the Charges	 */
	protected double[][] Points;

	/**Amounts of the Charges	 */
	protected double[] Charges;

	////////////////////////////////////////////////////////////////////////////
	/// #region : Constructors, calling each other using this()/super() (not in Interfaces)
	////////////////////////////////////////////////////////////////////////////
	
	/**Constructor that takes the Charges and it's Coordinates.
	 * The Charges are not integrated into the Vectors as n+1 Dimension,
	 * because the Vectors wouldn't transform correctly anymore!	 */
	public fChargeField(double[][] Points, double[] Charges) {
		if ((numCharges = Charges.length) != Points.length) throw new AbstractMethodError();
		this.Points  = VectorDouble.SET_DIM_AT(Points, 2); //ensure the Vectors all have 2 Dimensions!
		this.Charges = Charges;
	}

	////////////////////////////////////////////////////////////////////////////
	/// #region : Interface IFloatVectorFunction: Implementation
	////////////////////////////////////////////////////////////////////////////
	
	/**This Function represents the Charge Field Function.
	 * It returns the Force Field Vector generated by the Charges.
	 * The Potential is ~1/|dist|
	 * The Force Field is ~1/|dist|^(1/2), so ~dist/|dist|^(3/2)
	 */
	public double[] map(final double[] arg, final double[] out) {
		int i = numCharges; //
		VectorDouble.ZERO_AT(out);
		while (--i >= 0) {	//transform it to a Coordinate System with Points[i] in the Origin
			final double[] diff = VectorDouble.SUB(arg, Points[i]); 
			final double dist = VectorDouble.NORM_SQR(diff);
			VectorDouble.ADD_PROD_AT(out, Charges[i]/(dist * Math.sqrt(dist)), diff);
		}
		return out; }

	/**This Function represents the Charge Field Function.
	 * It returns the Force Field Vector generated by the Charges.
	 * The Potential is ~1/|dist|
	 * The Force Field is ~1/|dist|^(1/2), so ~dist/|dist|^(3/2)
	 */
	public float[] map(final float[] arg, final float[] out) {
		VectorFloat.ZERO_AT(out);
		for (int i = numCharges; --i >= 0;) {	//transform it to a Coordinate System with Points[i] in the Origin
			final float[] diff = VectorFloat.SUB(arg, Points[i]); 
			final float dist = (float) VectorFloat.NORM_SQR(diff);
			VectorFloat.addProdAt(out, Charges[i]/(dist * Math.sqrt(dist)), diff);
		}
		return out; }

}
