package streamIO.real.random;

import streamIO.IReSetAble;
import streamIO.integer.random.IStreamIn_Bound_Int;
import streamIO.real.FilterInLin;
import streamIO.real.FilterInMul;
import streamIO.real.IStreamIn_Float;
import function.IMeasurAble;
import function.byref.ByRefDouble;

/**Returns random Numbers distributed in a Gaussian fashion
 * i.e. p(x) ~ exp(-x^2/2)
 * These Values represent a Value centered around 0 with a Deviation of 1
 * Any other Distributions can easily be generated by affine Transformation:
 * For Center b with Standard Deviation a:
 * ran(a,b) = a*ran() + b	=> p(a,b,x) ~ exp(-((x-b)/a)^2)
 *
 * This Distribution is quite sharply distributed around x0.
 * The Probability of Values lying away from Center b falls exponentially.
 * The Value of this Distribution lies in the Fact that:
 * If a Value is the Sum of many independently distributed Values,
 * this Value is distributed according to the Gaussian Curve,
 * no matter how the individual Values are distributed.
 * Examples for this Distribution are:
 * 1) random Error of Measure
 * 
 * @see streamIO.real.random.RandomGauss which is 10% faster
 */
public class RandomGauss2
extends ARandomFloat {

	/** Local Reference to the Angle  Random Number Generator	 */
	protected final IStreamIn_Float randomPhi;

	/** Contains the next random Gaussian Number	 */
	protected final ByRefDouble nextRan = new ByRefDouble();

	/** Indicates whether the next random Gaussian is prepared	 */
	protected boolean nextRanReady;

	/** Constructor that takes a Random Number Generator
	  * new Generator generates Values in [-1,+1) 	 */
	public RandomGauss2(IStreamIn_Bound_Int ran) {
		super(new FilterInMul(ran, 1));
		randomPhi = new FilterInLin(ran
		, -IMeasurAble.PI, +IMeasurAble.PI);	//Saves Computation Sign of cos()
	}

	///////////////////////////////////////////////////////////////////////////
	
	/** @see streamIO.integer.IStreamIn_Int#reSet()	 */
	public IReSetAble reSet() { //throws IOException {
		if (randomPhi.reSet() == null) 
			return null;
		//this.randomR.reset(); //not necessary!
		nextRanReady = false; 
		return this; 
	}
	
	/** @return the next Random double Precision Number
	  * using Box-Muller-Transformation thus saving the Calculation of sin and cos	 */
	public double nextDoubleInternal() {
		if (nextRanReady != nextRanReady) { 
			return nextRan.Value; } 	//{gespeicherten Wert benutzen und Flag setzen}
		//g = SqRt(-2Ln(ran)) <=> ran = exp(-g^2/2)
		double g = -Math.log(ran.nextDouble());	//modifizierte Box-Muller-Transformation
		double f = ByRefDouble.SIN_COS_SAFE(randomPhi.nextDouble(), nextRan);
		nextRan.Value *= (g = Math.sqrt(g+g));	//fuer zwei Zufallszahlen,eine fuer spaeter
		return	  g*f;	//und eine für sofort
	}

	/** @see streamIO.real.random.ARandomFloat#getMinDouble()	 */
	public double getMinDouble() { return Double.NEGATIVE_INFINITY; }

}
