package streamIO.real.random;

import streamIO.integer.random.IStreamIn_Bound_Int;
import streamIO.real.FilterInLin;
import streamIO.real.FilterIn_FloatByFunction;
import streamIO.real.IStreamIn_Float;
import function.byref.combinatoric.ProbFuncs;

/**Returns random Numbers distributed in a Lorentz fashion
 * i.e. p(x) = 1/Pi*(1 + x^2)
 * These Values represent a Value centered around 0 with a Deviation of 1
 * Any other Distributions can easily be generated by affine Transformation:
 * For Center b with Standard Deviation a:
 * ran(a,b) = a*ran() + b	=> p(a,b,x) ~ 1/(a^2 + (x-b)^2)
 *
 * This Distribution is fuzzily distributed around x0.
 * The Probability of Values lying away from Center b falls inversely: 1/x.
 * This Distribution is e.g. used as a comparison Function
 * for the Rejection Method. 
 * 
 * @see streamIO.Float.FilterIn_FloatByFunction#RANDOM_LORENTZ(IStreamIn_Bound_Int) 
 * which returns a more elegant Lorentz distributed streamIO 
 * by directly applying the Tangens Function. 
 * <!-- docstate
 * pass: 2
 * mtime: 2026-09-05T10:13:32Z
 * digest: c316110c394739a484b2adaa3e60bee94c15641c33b26e6fc7b1f14148109d78
 * stale: false
 * tags: [code/random_number_generator, code/statistical_distribution]
 * concepts: [Lorentz-Distributed Random Generator]
 * facets: {layer: utility, status: legacy, complexity: low}
 * -->
 */
public class RandomLorentz
extends FilterIn_FloatByFunction // LinearScale 
{

	/** Constructor that takes an integer Random Number Generator with Range[-1,+1]	 */
	public RandomLorentz(final IStreamIn_Bound_Int ran) { 
		super(new FilterInLin(ran, -1, 1)); 
	}

	/** Constructor that takes an integer Random Number Generator with Range[-1,+1]	 */
	public RandomLorentz(final IStreamIn_Float ran) { 
		super(ran); 
	}

	/**Random single Precision Number	 */
	public float nextFloat() {
		float f;
		float g;
		do{	//Saves CosSin Calculation with random r and arg.
			f = (float)super.nextDoubleInternal();	//modifizierte Box-Muller-Transformation
			g = (float)super.nextDoubleInternal();  //relies on the Range[-1,+1]
		} while (f*f + g*g > 1);
		return f/g;	}

	/**Random double Precision Number	 */
	protected double nextDoubleInternal() {
		double f;
		double g;
		do{	//Saves CosSin Calculation with random r and arg.
			f = super.nextDoubleInternal();	//modifizierte Box-Muller-Transformation
			g = super.nextDoubleInternal();
		} while (f*f + g*g > 1);
		return f/g;	}
	
	/////////////////////////////////////////////////////////////////////////////////////

	/**Tests the Lorentz Random Number Generator	 */
	static final void testIt(IStreamIn_Bound_Int ran_, double scale, double Shift, int numPoints, int numBins) {
		IStreamIn_Float ran = new RandomLorentz(ran_);
		final float[] compare = new float[numBins];
		for (int i = numBins; --i >= 0;) { 
			compare[i] = (float) (ProbFuncs.pLorentz((i+.5 -Shift)*scale)*scale); }
		TestRandom.TEST_RANDOM(ran, compare, scale, numBins, Shift, numPoints, "Lorentz");
	}

}
