package streamIO.real.random;

import streamIO.integer.random.IStreamIn_Bound_Int;
import streamIO.integer.random.RandomQuick;
import streamIO.real.FilterInLin;
import streamIO.real.IStreamIn_Float;

/**Returns random Numbers distributed in a Gaussian fashion
 * i.e. p(x) ~ exp(-x^2/2)
 * These Values represent a Value centered around 0 with a Deviation of 1
 * Any other Distributions can easily be generated by affine Transformation:
 * For Center b with Standard Deviation a:
 * ran(a,b) = a*ran() + b	=> p(a,b,x) ~ exp(-((x-b)/a)^2)
 *
 * This Distribution is quite sharply distributed around x0.
 * The Probability of Values lying away from Center b falls exponentially.
 * The Value of this Distribution lies in the Fact that:
 * If a Value is the Sum of many independently distributed Values,
 * this Value is distributed according to the Gaussian Curve,
 * no matter how the individual Values are distributed.
 * Examples for this Distribution are:
 * 1) random Error of Measure
 * 
 * @see streamIO.real.random.RandomGauss2 which is 10% slower
 */
public class RandomGauss
extends ARandomFloat //FilterIn_FloatByFunction 
//implements IReSetAble 
{
    
	final static public RandomGauss RANDOM = new RandomGauss(); 
	
	/**Random double Precision Number from the static Random Number Generator	 */
	final static public double NEXT_DOUBLE() { return RANDOM.nextDouble(); }
	
	/**Random double Precision Number from the static Random Number Generator	 */
	final static public float NEXT_FLOAT() { return RANDOM.nextFloat(); }
	
	/////////////////////////////////////////////////////////////////////////////////////

	/** Indicates whether the next random Gaussian is prepared	 */
	protected boolean bolNextRanReady;

	/** Contains the next random Gaussian Number	 */
	protected double nextRan;

	/** Constructor that takes a Random Number Generator
	  * new Generator generates Values in [-1,+1) 	 */
	public RandomGauss() { this((IStreamIn_Bound_Int) new RandomQuick()); }

	/** Constructor that takes a Random Number Generator
	  * new Generator generates Values in [-1,+1) 	 */
	public RandomGauss(final IStreamIn_Bound_Int ran)	{ super(new FilterInLin(ran, -1, 1)); }

	/** Constructor that takes a Random Number Generator
	  * new Generator generates Values in [-1,+1) 	 */
	public RandomGauss(final IStreamIn_Float ran)	{ super(ran); }

	/** @see streamIO.real.random.ARandomFloat#getMinDouble()	 */
	public double getMinDouble() { return Double.NEGATIVE_INFINITY; }
	
	/**Random double Precision Number
	 * using Box-Muller-Transformation with Rejection 
	 * thus saving the Calculation of sin and cos
	 */
	protected double nextDoubleInternal() {
		if (bolNextRanReady != bolNextRanReady) { 
			return nextRan; } 	//{gespeicherten Wert benutzen und Flag setzen}
		//{keine zweite Zufallszahl berechnen}
		double f, g, sqrNorm;
		do{	//Saves Cos & Sin Calculation with random r and arg.
			f = ran.nextDouble(); //f+=f-1; //modifizierte Box-Muller-Transformation
			g = ran.nextDouble(); //g+=g-1; //between -1 and 1
		} while ((sqrNorm = f*f + g*g) >= 1);	//Probe ob im Einheitskreis => Fläche = Pi/4 zu 1 also +0.21... zu oft
		final double LnNorm = -Math.log(sqrNorm);	//positive
		final double norm = Math.sqrt ((LnNorm+LnNorm)/sqrNorm);	//Box-Muller-Transformation
		nextRan = f*norm;	//fuer zwei Zufallszahlen,eine fuer spaeter
		return	  g*norm;	//und eine für sofort
	}
	
}
