
(object Petal
    version    	42
    _written   	"Rose 4.5.8163.3"
    charSet    	0)

(object SubSystem "Group"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"36BB25E0024F"
    visible_modules 	(list dependency_list
	(object Dependency_Relationship
	    quid       	"36BB29F80379"
	    supplier   	"Component View::BaseCopy"
	    quidu      	"36BABF4B0011"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "intHalfGroup" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\intHalfGroup.java"))
	    quid       	"36BB25E002A9"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BEFD3D0183"
		    supplier   	"Logical View::Group::intHalfGroup"
		    quidu      	"36BB25E30376"))
	    language   	"Java")
	(object module "intGroup" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\intGroup.java"))
	    quid       	"36BB25EA02B8"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BEFD3A0020"
		    supplier   	"Logical View::Group::intGroup"
		    quidu      	"36BB25ED037A"))
	    language   	"Java")
	(object module "Group" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\Group.java"))
	    quid       	"36BB25F401E0"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BEFD36030A"
		    supplier   	"Logical View::Group::Group"
		    quidu      	"36BB25F702B6"))
	    language   	"Java")
	(object module "absGroup" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\absGroup.java"))
	    quid       	"36BB25FE01EE"
	    stereotype 	""
	    language   	"Java")
	(object module "HalfGroup" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\HalfGroup.java"))
	    quid       	"36BB260803DD"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB29F90013"
		    supplier   	"Component View::BaseCopy::copyAble"
		    quidu      	"36BABF500108"
		    supplier_is_spec 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BEFD30015C"
		    supplier   	"Logical View::Group::HalfGroup"
		    quidu      	"36BB260C00B8"))
	    language   	"Java")
	(object module "absHalfGroup" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\absHalfGroup.java"))
	    quid       	"36BB261202FB"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB2A0B0249"
		    supplier   	"Component View::BaseCopy::absCopyAble"
		    quidu      	"36BABF55012E"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "testGroup" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Group\\testGroup.java"))
	    quid       	"37BC919401D0"
	    stereotype 	""
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "Group"
	    quid       	"37BEFD2101B5"
	    title      	"Group"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::Group::testGroup" "NotAModuleType" "NotAModulePart" @1
		    location   	(186, 155)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(151, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"testGroup")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC919401D0"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::Group::absHalfGroup" "NotAModuleType" "NotAModulePart" @2
		    location   	(620, 155)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(573, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	174
			label      	"absHalfGroup")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB261202FB"
		    width      	314
		    autoResize 	TRUE
		    width      	314
		    height     	162)
		(object ModView "Component View::Group::HalfGroup" "NotAModuleType" "NotAModulePart" @3
		    location   	(589, 527)
		    label      	(object ItemLabel
			Parent_View 	@3
			location   	(554, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"HalfGroup")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB260803DD"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Group::HalfGroup" @4
		    location   	(589, 930)
		    label      	(object ItemLabel
			Parent_View 	@4
			location   	(588, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"HalfGroup")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB260C00B8"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @5
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BEFD30015C"
		    client     	@3
		    supplier   	@4
		    line_style 	0)
		(object ModView "Component View::Group::absGroup" "NotAModuleType" "NotAModulePart" @6
		    location   	(1054, 155)
		    label      	(object ItemLabel
			Parent_View 	@6
			location   	(1019, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"absGroup")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25FE01EE"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::Group::Group" "NotAModuleType" "NotAModulePart" @7
		    location   	(186, 527)
		    label      	(object ItemLabel
			Parent_View 	@7
			location   	(151, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"Group")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25F401E0"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Group::Group" @8
		    location   	(186, 930)
		    label      	(object ItemLabel
			Parent_View 	@8
			location   	(185, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"Group")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25F702B6"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @9
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BEFD36030A"
		    client     	@7
		    supplier   	@8
		    line_style 	0)
		(object ModView "Component View::Group::intGroup" "NotAModuleType" "NotAModulePart" @10
		    location   	(961, 527)
		    label      	(object ItemLabel
			Parent_View 	@10
			location   	(926, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"intGroup")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25EA02B8"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Group::intGroup" @11
		    location   	(961, 930)
		    label      	(object ItemLabel
			Parent_View 	@11
			location   	(960, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intGroup")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25ED037A"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @12
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BEFD3A0020"
		    client     	@10
		    supplier   	@11
		    line_style 	0)
		(object ModView "Component View::Group::intHalfGroup" "NotAModuleType" "NotAModulePart" @13
		    location   	(1302, 527)
		    label      	(object ItemLabel
			Parent_View 	@13
			location   	(1261, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"intHalfGroup")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25E002A9"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object InterfaceView "Logical View::Group::intHalfGroup" @14
		    location   	(1302, 930)
		    label      	(object ItemLabel
			Parent_View 	@14
			location   	(1301, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intHalfGroup")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB25E30376"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @15
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BEFD3D0183"
		    client     	@13
		    supplier   	@14
		    line_style 	0)))))
