prop1=property1
#Properties can NOT be referenced in Java (unlike ANT)!
prop2=${prop1}
prop3=./nested.properties
#Example of how to include the String ${ in a Property without having it replaced! 
dollarRef=${
prop4=${dollarRef}etc}