package streamIO.copy.group.ring.metric;

import streamIO.copy.group.ring.Extrapolator;
import streamIO.copy.group.ring.IIntRing;
import streamIO.copy.order.IOrder;
import streamIO.copy.order.IntervalOrd;
import function.ICountAble;
import function.IFunction;

/**Extends Extrapolator with an Evaluation, if the Extrapolation converges
 * and if yes, to which Value it converges.
 * Only now is it possible to define Methods that can calculate Limits
 * <!-- docstate
 * pass: 2
 * mtime: 2026-09-05T10:13:24Z
 * digest: 7efb6e6bddb46c376a3220bdea35c259f20d40a665e751166ec8ed9b60c54d8f
 * stale: false
 * tags: [code/metric_space, code/root_finding, code/numerical_integration, code/big_integer_arithmetic]
 * concepts: [Metric Spaces - Root Finding and Numerical Integration]
 * facets: {layer: domain, status: legacy, complexity: high}
 * -->
 * by themselves, because Convergence cannot be defined without a Metric.  */
public class ExtraPolValue
extends Extrapolator {

	/**Absolute Value to compare the deviation from the last Extrapolation to.	 */
	protected IMetricIRing Compare;

	/**Interval of the previous Values	 */
	protected IntervalOrd intrvl;

	/**Flag for convergence	 */
	protected boolean converge;

	/**Constructor	 */
	public ExtraPolValue (int MaxGrad, int Power, boolean rational) {
		super (MaxGrad, Power, rational);}

	/**Constructor, defaults the Convergence Power to 1 (linear Convergence)	 */
	public ExtraPolValue (int MaxGrad, boolean rational) {
		super(MaxGrad, Power, rational);}

	/**Constructor, defaults the 'rational' Switch 	 */
	public ExtraPolValue (int MaxGrad, int Power) {
		this(MaxGrad, Power, rational);}

	/**Constructor, defaults the 'rational' Switch 	 */
	public ExtraPolValue (int Power) { this(MaxGrad, Power, rational);}

	/**Empty Constructor, defaults all. 	 */
	public ExtraPolValue () { this(MaxGrad, Power, rational);}

	/**Reset the Extrapolator, so a new Extrapolation can be performed.	 */
	public void reset(int Power, boolean rational) {
		super.reset(Power, rational); intrvl = null; }

	/**Reset the Extrapolator, so a new Extrapolation can be performed.	 */
	public void reset(int Power) { reset(Power, rational); }

	/**Reset the Extrapolator, so a new Extrapolation can be performed.	 */
	public void reset(boolean rational) { reset(Power, rational); }

	/**Reset the Extrapolator, so a new Extrapolation can be performed.	 */
	public void reset() { reset(Power, rational); }

	/**Adding a pair of Values to the Extrapolator.
	 * These Values are changed during Calculation, so better make copies beforehand.
	 * Returns convergence or maximum number of Pairs.
	 */
	public boolean addPoint(IIntRing x, IIntRing y) {
		//{Das Feld wird von hinten aufgefuellt und berechnet}
		if (Compare == null) Compare = ((IMetricIRing) y).mulAbsAccuracy();
		boolean maxPt = super.addPoint(x, y);	//This Method only returns true, when the max. number of points is reached
		if (intrvl == null) {intrvl = new IntervalOrd((IOrder) yDat[0], (IOrder) yDat[0]); return false;}
		else intrvl.addPoint (yDat[0]);		//Hilf contains the Difference to the old Value
		return  (converge = Compare.notLessThan(((IMetricIRing) Hilf).AbsVAt()))	//prevent early evaluation, calculate this first!
				|| maxPt; //{stets 2 Extrapolationsschritte}
	}

	/**Does a more thorough Evaluation of the Extrapolation Behavior
	 * to distinguish between Convergence, definite and indefinite Divergence.
	 */
	public IIntRing Evaluation() {
		IMetricIRing f_alt = (IMetricIRing) yDat[0];
		if (mDim < MaxGrad) return f_alt;       //{evtl. Divergenz}
		if (converge) return f_alt;
		if (intrvl.Position(f_alt) == 0) return null;	//unbestimmt divergent!
		if (f_alt.isMoreThan(alt))return (IIntRing) f_alt.   Infinity();	//  bestimmt divergent!
		else				return (IIntRing) f_alt.NegInfinity();	//for this you need MetricBody Methods!
	}

	/**Calculates the Limes of a Series.
	 * The Parameter Power determines the assumed Error Power Series.
	 * The Parameter rational determines,
	 * whether rational or polynomial Approximation is used.
	 * The Series will be generated by a ByRefLong, starting with 1.	 */
	public IIntRing Limes(IIntRing testObject, IFunction F, int Power, boolean rational) {
		reset(Power, rational);
		IIntRing Zaehler = (IIntRing) testObject.one();
		//  ByRefLong Zaehler = new ByRefLong (1);
		IIntRing PSum = (IIntRing) F.Map(Zaehler);
		IIntRing Position = (IIntRing) PSum.one();
		addPoint(Position, PSum);
		boolean Ende;
		do {
			Zaehler . dblAt(); //Zaehler.Value <<= 1;
			Position.halfAt();
			Ende = addPoint (Position, (IIntRing) F.Map(Zaehler));
		} while (! Ende);
		return Evaluation();
	}

	/**Calculates the Sum of a Series.
	 * The Parameter Power determines the assumed Error Power Series.
	 * The Parameter rational determines,
	 * whether rational or polynomial Approximation is used.
	 * The Series will be generated by a ByRefLong, starting with 1.	 */
	public IIntRing Reihe(IIntRing testObject, IFunction F, int Power, boolean rational) {
		reset(Power, rational);
		int Z1 = 1;
		IIntRing Zaehler = (IIntRing) testObject.one();
		//  ByRefLong Zaehler = new ByRefLong (1);
		IIntRing PSum = (IIntRing) F.Map(Zaehler); //{Partial-Summen ab 1}
		IIntRing Position = (IIntRing) PSum.one();
		addPoint(Position, PSum);
		boolean Ende;
		do {
			Z1 <<= 1;
			Position.halfAt();
			while (((ICountAble)Zaehler).getInt() < Z1)
				PSum.addAt (F.Map(Zaehler.inc()));   //{PartialSumme von 1..Z bleibt}
			Ende = addPoint(Position, PSum);
		} while (! Ende);
		return Evaluation(); }

	/**Calculates the Product of the Series.
	 * The Factors must converge to 1 fast enough.
	 * The Logarithm of the Product is simply the Sum of the Logarithms of the Factors	 */
/*	FUNCTION Produkt;

	 VAR P_Sig  : Boolean;
	     P_Func : Folge;

	{
		 P_Func = P_H_Func;P_H_Func = f;
		 P_Sig = Sig;Sig = FALSE;
		 Summe = Exp (Reihe (H_Produkt));
		 IF Sig
		  THEN Produkt = +Summe
		  ELSE Produkt = -Summe;
		 P_H_Func = P_Func;
		 Sig = P_Sig;
	}
*/

	/**Calculates the Limes of a Function when it's Value converges to x0	 */
	public IIntRing lim (IFunction F, IIntRing x0, IIntRing h) {
		//{f (x0+h) = f (x0)+h*f' (x0)+h�*f'' (x0)+... }
		reset();
//		MetricIRing one = (MetricIRing) h.one();
//		IIntRing Help = (one.less(h))? (IIntRing) one.divAt(h) : h;
		boolean Ende;
		do {
//  		Compare.MaxAt (f_alt.absV());
			Ende = addPoint (Hilf, (IIntRing) F.Map(x0.add(h)));
			h.mulAt (h);Hilf.sqrAt();
		} while (! Ende);
		return Evaluation (); }

	//////////////
	//  Testing	//
	//////////////

	/**Method to test all Implementations in this class.	 */
	public static void testIt() {	//Code commented out to reduce Dependency between Metric and RingFuncs
//		IIntRing xl = (IIntRing) ACopyAble.testInstance.copy();
		System.out.println("Testing ExtraPolValue:");
		System.out.println("Searching for the Limit of 1/n:");
/*		ExtraPolValue EPV = new ExtraPolValue(8, 1);	//need at least 8 Iterations for Accuracy of 10 Digits.
		System.out.println("Rational,	Grad 1: " + EPV.Limes(xl, RingFuncs.Inv.Inv, 1, true ));
		System.out.println("Polynomial,	Grad 1: " + EPV.Limes(xl, RingFuncs.Inv.Inv, 1, false));
		System.out.println("Rational,	Grad 2: " + EPV.Limes(xl, RingFuncs.Inv.Inv, 2, true ));
		System.out.println("Polynomial,	Grad 2: " + EPV.Limes(xl, RingFuncs.Inv.Inv, 2, false));
		System.out.println("Searching for the Limit of e:");
		System.out.println("...as the Limit of (1+1/n)^n");
		System.out.println("Rational,	Grad 1: " + EPV.Limes(xl, new RingFuncs.fEulerFktn(), 1, true ));
		System.out.println("Polynomial,	Grad 1: " + EPV.Limes(xl, new RingFuncs.fEulerFktn(), 1, false));
		System.out.println("Rational,	Grad 2: " + EPV.Limes(xl, new RingFuncs.fEulerFktn(), 2, true ));
		System.out.println("Polynomial,	Grad 2: " + EPV.Limes(xl, new RingFuncs.fEulerFktn(), 2, false));
		System.out.println("...as the Sum of 1/n!");
		System.out.println("Rational,	Grad 1: " + EPV.Reihe(xl, new RingFuncs.fEulerSum(), 1, true ));
		System.out.println("Polynomial,	Grad 1: " + EPV.Reihe(xl, new RingFuncs.fEulerSum(), 1, false));
		System.out.println("Rational,	Grad 2: " + EPV.Reihe(xl, new RingFuncs.fEulerSum(), 2, true ));
		System.out.println("Polynomial,	Grad 2: " + EPV.Reihe(xl, new RingFuncs.fEulerSum(), 2, false));
		System.out.println("Searching for the geometric Sum (n, a^n for |a| < 1)");
		System.out.println("...for a = 0.25");
		RingFuncs.fGeoSum Sum = new RingFuncs.fGeoSum(((IIntRing)xl.one()).halfAt().halfAt());
		System.out.println("Rational,	Grad 1: " + EPV.Reihe(xl, Sum, 1, true ));
		System.out.println("Polynomial,	Grad 1: " + EPV.Reihe(xl, Sum, 1, false));
		System.out.println("Rational,	Grad 2: " + EPV.Reihe(xl, Sum, 2, true ));
		System.out.println("Polynomial,	Grad 2: " + EPV.Reihe(xl, Sum, 2, false));
*/		}

}
