
(object Petal
    version    	42
    _written   	"Rose 4.5.8054.1"
    charSet    	0)

(object SubSystem "intFunction"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"36BB39470388"
    documentation 	"Defines Interfaces and (abstract) Classes for (InvertAble) mapping Objects to Objects as well as Real Numbers to Real Numbers. "
    physical_models 	(list unit_reference_list
	(object module "Identity" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intFunction\\Identity.java"))
	    quid       	"36BB39BA0025"
	    stereotype 	""
	    language   	"Java")
	(object module "functionAble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intFunction\\functionAble.java"))
	    quid       	"36BB39BA0075"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF036000B0"
		    supplier   	"Logical View::intFunction::functionAble"
		    quidu      	"36BB39BA0076"))
	    language   	"Java")
	(object module "intFunction" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intFunction\\intFunction.java"))
	    quid       	"36BB39BA00B1"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF035D0001"
		    supplier   	"Logical View::intFunction::intFunction"
		    quidu      	"36BB39BA00B2"))
	    language   	"Java")
	(object module "absFunction" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intFunction\\absFunction.java"))
	    quid       	"37BC8EB901EF"
	    stereotype 	""
	    language   	"Java")
	(object module "Function" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intFunction\\Function.java"))
	    quid       	"37BC919D03DB"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF03570306"
		    supplier   	"Logical View::intFunction::Function"
		    quidu      	"37BC919D03E5"))
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "intFunction"
	    quid       	"37BF034F023C"
	    title      	"intFunction"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::intFunction::Function" "NotAModuleType" "NotAModulePart" @1
		    location   	(186, 527)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(151, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"Function")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC919D03DB"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::intFunction::Function" @2
		    location   	(186, 930)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(185, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"Function")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC919D03E5"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @3
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF03570306"
		    client     	@1
		    supplier   	@2
		    line_style 	0)
		(object ModView "Component View::intFunction::absFunction" "NotAModuleType" "NotAModulePart" @4
		    location   	(217, 155)
		    label      	(object ItemLabel
			Parent_View 	@4
			location   	(173, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	162
			label      	"absFunction")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC8EB901EF"
		    width      	292
		    autoResize 	TRUE
		    width      	292
		    height     	162)
		(object ModView "Component View::intFunction::intFunction" "NotAModuleType" "NotAModulePart" @5
		    location   	(930, 527)
		    label      	(object ItemLabel
			Parent_View 	@5
			location   	(886, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	162
			label      	"intFunction")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB39BA00B1"
		    width      	292
		    autoResize 	TRUE
		    width      	292
		    height     	162)
		(object InterfaceView "Logical View::intFunction::intFunction" @6
		    location   	(930, 930)
		    label      	(object ItemLabel
			Parent_View 	@6
			location   	(929, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intFunction")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB39BA00B2"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @7
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF035D0001"
		    client     	@5
		    supplier   	@6
		    line_style 	0)
		(object ModView "Component View::intFunction::functionAble" "NotAModuleType" "NotAModulePart" @8
		    location   	(589, 527)
		    label      	(object ItemLabel
			Parent_View 	@8
			location   	(554, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"functionAble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB39BA0075"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::intFunction::functionAble" @9
		    location   	(558, 930)
		    label      	(object ItemLabel
			Parent_View 	@9
			location   	(557, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"functionAble")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB39BA0076"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @10
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF036000B0"
		    client     	@8
		    supplier   	@9
		    line_style 	0)
		(object ModView "Component View::intFunction::Identity" "NotAModuleType" "NotAModulePart" @11
		    location   	(651, 155)
		    label      	(object ItemLabel
			Parent_View 	@11
			location   	(616, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"Identity")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB39BA0025"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)))))
