
(object Petal
    version    	42
    _written   	"Rose 4.5.8163.3"
    charSet    	0)

(object SubSystem "Shiftable"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"36BB85D901BD"
    visible_modules 	(list dependency_list
	(object Dependency_Relationship
	    quid       	"36BB87580240"
	    supplier   	"Component View::BaseCopy"
	    quidu      	"36BABF4B0011"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC93D103C8"
	    supplier   	"Component View::ByRef"
	    quidu      	"36BB4AA503DA"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "iterable" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\iterable.java"))
	    quid       	"36BB85D901F9"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF059B0115"
		    supplier   	"Logical View::Shiftable::iterable"
		    quidu      	"36BB85D901FA"))
	    language   	"Java")
	(object module "intShiftable" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\intShiftable.java"))
	    quid       	"36BB85D902DF"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF059803C4"
		    supplier   	"Logical View::Shiftable::intShiftable"
		    quidu      	"36BB85D902E9"))
	    language   	"Java")
	(object module "shiftable" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\shiftable.java"))
	    quid       	"36BB85D903A8"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB87580241"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"36BB87BA0042"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"36BB8BD80282"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93D3005A"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD235C010C"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A3E03C3"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF05960385"
		    supplier   	"Logical View::Shiftable::shiftable"
		    quidu      	"36BB85D903B2"))
	    language   	"Java")
	(object module "ByRefBoolean" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"E:\\Personal\\Code\\Java\\Shiftable\\ByRefBoolean.java"))
	    quid       	"36BB85DA002E"
	    stereotype 	""
	    language   	"Java")
	(object module "ReverseIterator" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\ReverseIterator.java"))
	    quid       	"36BB85DA0128"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93D20370"
		    supplier   	"Component View::ByRef::ByRefLong"
		    quidu      	"36BB4E3D0116"
		    supplier_is_spec 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF05930019"
		    supplier   	"Logical View::Shiftable::ReverseIterator"
		    quidu      	"36BB85DA0132"))
	    language   	"Java")
	(object module "Iterator" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\Iterator.java"))
	    quid       	"36BB85DA01AA"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93D2033D"
		    supplier   	"Component View::ByRef"
		    quidu      	"36BB4AA503DA"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD2359019E"
		    supplier   	"Component View::ByRef"
		    quidu      	"36BB4AA503DA"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A3C0058"
		    supplier   	"Component View::ByRef"
		    quidu      	"36BB4AA503DA"
		    supplier_is_subsystem 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF059100AC"
		    supplier   	"Logical View::Shiftable::Iterator"
		    quidu      	"36BB85DA01B4"))
	    language   	"Java")
	(object module "absIterator" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\absIterator.java"))
	    quid       	"36BB85DA025F"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93D103C9"
		    supplier   	"Component View::ByRef::ByRefLong"
		    quidu      	"36BB4E3D0116"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "absShiftable" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\absShiftable.java"))
	    quid       	"36BB85DA0363"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB87BB026A"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"36BB8BDC033C"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93D201C1"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD235601AE"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A39005E"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BE553B0378"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BE564E0368"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "swapAble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\swapAble.java"))
	    quid       	"36BB85DB0007"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB87590241"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"36BB87BB02F6"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"36BB8BDD018F"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93D300B4"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD235D0186"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A400068"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF058B028F"
		    supplier   	"Logical View::Shiftable::swapAble"
		    quidu      	"36BB85DB0011"))
	    language   	"Java")
	(object module "IndexIterator" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\IndexIterator.java"))
	    quid       	"36BB85DB00A7"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93D201FD"
		    supplier   	"Component View::ByRef::ByRefLong"
		    quidu      	"36BB4E3D0116"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "absReverseIterator" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\Shiftable\\absReverseIterator.java"))
	    quid       	"37BE6A6C007E"
	    stereotype 	""
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "Shiftable"
	    quid       	"37BF057F004C"
	    title      	"Shiftable"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::Shiftable::absReverseIterator" "NotAModuleType" "NotAModulePart" @1
		    location   	(279, 155)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(220, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	222
			label      	"absReverseIterator")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BE6A6C007E"
		    width      	400
		    autoResize 	TRUE
		    width      	400
		    height     	162)
		(object ModView "Component View::Shiftable::IndexIterator" "NotAModuleType" "NotAModulePart" @2
		    location   	(744, 155)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(709, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"IndexIterator")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DB00A7"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::Shiftable::swapAble" "NotAModuleType" "NotAModulePart" @3
		    location   	(2232, 527)
		    label      	(object ItemLabel
			Parent_View 	@3
			location   	(2197, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"swapAble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DB0007"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Shiftable::swapAble" @4
		    location   	(2232, 930)
		    label      	(object ItemLabel
			Parent_View 	@4
			location   	(2231, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	232
			justify    	0
			label      	"swapAble")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DB0011"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @5
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF058B028F"
		    client     	@3
		    supplier   	@4
		    line_style 	0)
		(object ModView "Component View::Shiftable::absShiftable" "NotAModuleType" "NotAModulePart" @6
		    location   	(1178, 155)
		    label      	(object ItemLabel
			Parent_View 	@6
			location   	(1134, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	162
			label      	"absShiftable")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA0363"
		    width      	292
		    autoResize 	TRUE
		    width      	292
		    height     	162)
		(object ModView "Component View::Shiftable::absIterator" "NotAModuleType" "NotAModulePart" @7
		    location   	(1581, 155)
		    label      	(object ItemLabel
			Parent_View 	@7
			location   	(1546, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"absIterator")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA025F"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::Shiftable::Iterator" "NotAModuleType" "NotAModulePart" @8
		    location   	(279, 527)
		    label      	(object ItemLabel
			Parent_View 	@8
			location   	(244, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"Iterator")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA01AA"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Shiftable::Iterator" @9
		    location   	(155, 930)
		    label      	(object ItemLabel
			Parent_View 	@9
			location   	(154, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	232
			justify    	0
			label      	"Iterator")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA01B4"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @10
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF059100AC"
		    client     	@8
		    supplier   	@9
		    line_style 	0)
		(object ModView "Component View::Shiftable::ReverseIterator" "NotAModuleType" "NotAModulePart" @11
		    location   	(682, 527)
		    label      	(object ItemLabel
			Parent_View 	@11
			location   	(641, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"ReverseIterator")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA0128"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object InterfaceView "Logical View::Shiftable::ReverseIterator" @12
		    location   	(434, 930)
		    label      	(object ItemLabel
			Parent_View 	@12
			location   	(433, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	232
			justify    	0
			label      	"ReverseIterator")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA0132"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @13
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF05930019"
		    client     	@11
		    supplier   	@12
		    line_style 	0)
		(object ModView "Component View::Shiftable::ByRefBoolean" "NotAModuleType" "NotAModulePart" @14
		    location   	(1984, 155)
		    label      	(object ItemLabel
			Parent_View 	@14
			location   	(1943, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"ByRefBoolean")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85DA002E"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object ModView "Component View::Shiftable::shiftable" "NotAModuleType" "NotAModulePart" @15
		    location   	(1922, 527)
		    label      	(object ItemLabel
			Parent_View 	@15
			location   	(1887, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"shiftable")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85D903A8"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Shiftable::shiftable" @16
		    location   	(1891, 930)
		    label      	(object ItemLabel
			Parent_View 	@16
			location   	(1890, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	232
			justify    	0
			label      	"shiftable")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85D903B2"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @17
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF05960385"
		    client     	@15
		    supplier   	@16
		    line_style 	0)
		(object ModView "Component View::Shiftable::intShiftable" "NotAModuleType" "NotAModulePart" @18
		    location   	(1116, 527)
		    label      	(object ItemLabel
			Parent_View 	@18
			location   	(1072, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	162
			label      	"intShiftable")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85D902DF"
		    width      	292
		    autoResize 	TRUE
		    width      	292
		    height     	162)
		(object InterfaceView "Logical View::Shiftable::intShiftable" @19
		    location   	(775, 930)
		    label      	(object ItemLabel
			Parent_View 	@19
			location   	(774, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	232
			justify    	0
			label      	"intShiftable")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85D902E9"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @20
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF059803C4"
		    client     	@18
		    supplier   	@19
		    line_style 	0)
		(object ModView "Component View::Shiftable::iterable" "NotAModuleType" "NotAModulePart" @21
		    location   	(1519, 527)
		    label      	(object ItemLabel
			Parent_View 	@21
			location   	(1484, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"iterable")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85D901F9"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::Shiftable::iterable" @22
		    location   	(1519, 930)
		    label      	(object ItemLabel
			Parent_View 	@22
			location   	(1518, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	232
			justify    	0
			label      	"iterable")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB85D901FA"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @23
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF059B0115"
		    client     	@21
		    supplier   	@22
		    line_style 	0)))))
