package graphic.implement;

import graphic.Graph2D;
import graphic.Point2D;

import java.awt.Color;
import java.awt.Graphics;

/** Graphics Context that uses Dithering, choosing between two neighboring
 * palette colors per pixel based on a precomputed threshold matrix.
 * <p>Call {@link #init(Color[], byte)} once to build the matrix and install the
 * palette before drawing.
 *
 * <h2>Collaborators</h2>
 * <table>
 * <tr><th>Type</th><th>Relationship</th></tr>
 * <tr><td>{@link Graph2D}</td><td>superclass; supplies the pixel/line drawing primitives this class colors</td></tr>
 * </table>
 * @see Graph2D
 * <!-- docstate
 * pass: 2
 * mtime: 2026-09-05T11:47:47Z
 * digest: c4bf9e6d8a422fc51e7be2f6f5965685a5accffd8d11ca1fb9c32d56e16ff0ec
 * stale: false
 * tags: [code/graphics, code/algorithm]
 * concepts: [Dithering Color Strategy]
 * facets: {layer: utility, status: broken, complexity: medium}
 * -->
 */
public class GrayColor
extends Graph2D {
	
	/** Dithering threshold matrix generated by {@link #init(Color[], byte)},
	 * indexed by the masked x and y coordinates. */
	int[][] grayMatrix;
	/** Palette installed by {@link #init(Color[], byte)}, indexed by the color code computed in {@link #setColor(int)}. */
	Color[] grayPalette;
	/** Bit shift width used to derive {@link #koordMaske} and {@link #grayMaske} from {@link #maxGrayShift}. */
	int grayShift;
	/** Bitmask that extracts the dithering fraction from a packed color value. */
	int grayMaske;

	/**Binary Value for masking the higher Bits of the x and y Coordinates	 */
	int koordMaske;

	/**Maximum Value for the GrayShift_:	 */
	byte maxGrayShift = 15;

	/**Initializing Constructor	with Default Clipping Area  */
	public GrayColor(final Graphics g){ super (g); }

	/**Constructor that defines a Clipp�ng Area		 */
	public GrayColor(final Graphics g_, final Point2D ClipTL_, final Point2D ClipBR_){
		super (g_, ClipTL_, ClipBR_); }

	/**Generates the Gray Matrix of given GrayShift_ <=4.	 */
	public void init(final Color[] GP, byte grayShift_) {
		if (grayShift_ > maxGrayShift ) {
			grayShift_ = maxGrayShift;} 
		grayShift  = grayShift_;
		koordMaske = (1 << grayShift)-1;
		grayMaske  = (1 << (grayShift << 1))-1;	//Always switching between two neighboring Colors
		grayPalette = GP;
		grayMatrix = new int[1+koordMaske][1+koordMaske];
		grayMatrix[0][0] = 0;
		int i = 0;
		int j = grayShift_-1;
		for (int Z1 = -1; ++Z1 <= j;) {
			for (int Z2 = 2; --Z2 >= 0;) { //Values 1 and 0 for the Rows
				for (int Z3 = 2; --Z3 >= 0;) {  //Values 1 and 0 for the Columns
					initPass(i, Z2 << Z1, Z3 << Z1, ((Z2 <<  1) + Z3*3) & 3);
				}
			}
			i = ((i+1) << 1)-1;	//extend the BitMask, so it contains 0001 0011 0111...
		}
	}

	/** Fills one diagonal quadrant of {@link #grayMatrix} from the already-computed
	 * smaller block, offset by the given increment.
	 * @see #init(Color[], byte) uses this Method exclusively 	 */
	private void initPass(int i, final int x0, final int y0, final int increment) {
		for (int Z4 = -1; ++Z4 <= i;) {
			for (int Z5 = -1; ++Z5 <= i;) {
				// TODO: LOGIC: `<<` binds looser than `+` in Java, so this evaluates as
				// `grayMatrix[Z4][Z5] << (2 + increment)` instead of the presumably intended
				// `(grayMatrix[Z4][Z5] << 2) + increment` (a base-4 accumulation matching the
				// 0..3 range of increment). Verify against the dithering algorithm this ports.
				grayMatrix[Z4+x0][Z5+y0] = grayMatrix[Z4][Z5] << 2 + increment;
			}
		}
	}

	/** Base color index for the current pixel, derived by {@link #setColor(int)}. */
	int farbCode;
	/** Dithering fraction bits extracted from the current color by {@link #setColor(int)}. */
	int FarbMask;

	/** Splits the given packed color value into {@link #farbCode} and {@link #FarbMask} for dithering.
	 * @param farbe packed color value combining a base color index and a dithering fraction. */
	public void setColor(int farbe) {
		farbCode = farbe >>> (grayShift << 1);
		FarbMask = farbe &	  grayMaske;
	}

	/** Selects the dithered {@link Color} for the current pixel from {@link #grayMatrix} and delegates to the superclass. */
	public void setPixel() {
		int fCode = farbCode;
		if (FarbMask >= grayMatrix[P.getX() & koordMaske][P.getY() & koordMaske]) {
			++fCode; } 
		setColor (grayPalette[fCode]);
		super.setPixel ();
	}

}
