
(object Petal
    version    	42
    _written   	"Rose 4.5.8163.3"
    charSet    	0)

(object SubSystem "BaseCopy"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"36BABF4B0011"
    visible_modules 	(list dependency_list
	(object Dependency_Relationship
	    quid       	"37BC8EAD03B2"
	    supplier   	"Component View::java::io"
	    quidu      	"34B0F6CE0290"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "intCopyAble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BaseCopy\\intCopyAble.java"))
	    quid       	"36BABF4B006B"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC8EAE00D8"
		    supplier   	"Component View::java::io"
		    quidu      	"34B0F6CE0290"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD04C20111"
		    supplier   	"Component View::java::io"
		    quidu      	"34B0F6CE0290"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1BE902EB"
		    supplier   	"Component View::java::io"
		    quidu      	"34B0F6CE0290"
		    supplier_is_subsystem 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"36BC2CF9002C"
		    supplier   	"Logical View::BaseCopy::intCopyAble"
		    quidu      	"36BB22B90136"))
	    language   	"Java")
	(object module "copyAble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BaseCopy\\copyAble.java"))
	    quid       	"36BABF500108"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC8EAD03B3"
		    supplier   	"Component View::java::io"
		    quidu      	"34B0F6CE0290"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD04C10200"
		    supplier   	"Component View::java::io"
		    quidu      	"34B0F6CE0290"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1BE803B2"
		    supplier   	"Component View::java::io"
		    quidu      	"34B0F6CE0290"
		    supplier_is_subsystem 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"36BC2CF602D1"
		    supplier   	"Logical View::BaseCopy::copyAble"
		    quidu      	"36BB22B9021D"))
	    language   	"Java")
	(object module "absCopyAble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BaseCopy\\absCopyAble.java"))
	    quid       	"36BABF55012E"
	    stereotype 	""
	    language   	"Java")
	(object module "cachedProperty" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BaseCopy\\cachedProperty.java"))
	    quid       	"37BC8EAA0082"
	    stereotype 	""
	    language   	"Java")
	(object module "intCountable" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BaseCopy\\intCountable.java"))
	    quid       	"37BC8EAE00E2"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BEFCBA018F"
		    supplier   	"Logical View::BaseCopy::intCountable"
		    quidu      	"37BC8EAE00EC"))
	    language   	"Java")
	(object module "testBaseCopy" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BaseCopy\\testBaseCopy.java"))
	    quid       	"37BC8EAE00F6"
	    stereotype 	""
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "BaseCopy"
	    quid       	"36BC2CEA0338"
	    title      	"BaseCopy"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::BaseCopy::absCopyAble" "NotAModuleType" "NotAModulePart" @1
		    location   	(248, 155)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(198, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	187
			label      	"absCopyAble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BABF55012E"
		    width      	336
		    autoResize 	TRUE
		    width      	336
		    height     	162)
		(object ModView "Component View::BaseCopy::copyAble" "NotAModuleType" "NotAModulePart" @2
		    location   	(186, 527)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(151, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"copyAble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BABF500108"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::BaseCopy::copyAble" @3
		    location   	(186, 930)
		    label      	(object ItemLabel
			Parent_View 	@3
			location   	(185, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"copyAble")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB22B9021D"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @4
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"36BC2CF602D1"
		    client     	@2
		    supplier   	@3
		    line_style 	0)
		(object ModView "Component View::BaseCopy::intCopyAble" "NotAModuleType" "NotAModulePart" @5
		    location   	(620, 527)
		    label      	(object ItemLabel
			Parent_View 	@5
			location   	(573, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	174
			label      	"intCopyAble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BABF4B006B"
		    width      	314
		    autoResize 	TRUE
		    width      	314
		    height     	162)
		(object InterfaceView "Logical View::BaseCopy::intCopyAble" @6
		    location   	(620, 930)
		    label      	(object ItemLabel
			Parent_View 	@6
			location   	(619, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intCopyAble")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB22B90136"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @7
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"36BC2CF9002C"
		    client     	@5
		    supplier   	@6
		    line_style 	0)
		(object ModView "Component View::BaseCopy::cachedProperty" "NotAModuleType" "NotAModulePart" @8
		    location   	(713, 155)
		    label      	(object ItemLabel
			Parent_View 	@8
			location   	(669, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	162
			label      	"cachedProperty")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC8EAA0082"
		    width      	292
		    autoResize 	TRUE
		    width      	292
		    height     	162)
		(object ModView "Component View::BaseCopy::intCountable" "NotAModuleType" "NotAModulePart" @9
		    location   	(1023, 527)
		    label      	(object ItemLabel
			Parent_View 	@9
			location   	(973, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	187
			label      	"intCountable")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC8EAE00E2"
		    width      	336
		    autoResize 	TRUE
		    width      	336
		    height     	162)
		(object InterfaceView "Logical View::BaseCopy::intCountable" @10
		    location   	(1023, 930)
		    label      	(object ItemLabel
			Parent_View 	@10
			location   	(1022, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intCountable")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC8EAE00EC"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @11
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BEFCBA018F"
		    client     	@9
		    supplier   	@10
		    line_style 	0)
		(object ModView "Component View::BaseCopy::testBaseCopy" "NotAModuleType" "NotAModulePart" @12
		    location   	(1209, 155)
		    label      	(object ItemLabel
			Parent_View 	@12
			location   	(1156, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	199
			label      	"testBaseCopy")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC8EAE00F6"
		    width      	358
		    autoResize 	TRUE
		    width      	358
		    height     	162)))))
