
(object Petal
    version    	42
    _written   	"Rose 4.5.8054.1"
    charSet    	0)

(object SubSystem "intTest"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"36BC688202BD"
    documentation 	"Defines Interfaces and (abstract) Classes for Order Relation, Counting Measure Operators and Testers. "
    physical_models 	(list unit_reference_list
	(object module "testAble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\testAble.java"))
	    quid       	"36BC688202C8"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF085E00AD"
		    supplier   	"Logical View::intTest::testAble"
		    quidu      	"36BC688202D1"))
	    language   	"Java")
	(object module "intTester" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\intTester.java"))
	    quid       	"36BC6882032B"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF085C015F"
		    supplier   	"Logical View::intTest::intTester"
		    quidu      	"36BC68820335"))
	    language   	"Java")
	(object module "operable" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\operable.java"))
	    quid       	"36BC68820371"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF085A0152"
		    supplier   	"Logical View::intTest::operable"
		    quidu      	"36BC68820372"))
	    language   	"Java")
	(object module "intOperator" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\intOperator.java"))
	    quid       	"36BC688203AD"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF0858016D"
		    supplier   	"Logical View::intTest::intOperator"
		    quidu      	"36BC688203B7"))
	    language   	"Java")
	(object module "TestConst" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\TestConst.java"))
	    quid       	"36BC6883000B"
	    stereotype 	""
	    language   	"Java")
	(object module "TestObject" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\TestObject.java"))
	    quid       	"36BC6883006F"
	    stereotype 	""
	    language   	"Java")
	(object module "TestNumber" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\intTest\\TestNumber.java"))
	    quid       	"36BC688300B5"
	    stereotype 	""
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "intTest"
	    quid       	"37BF084A002C"
	    title      	"intTest"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::intTest::TestNumber" "NotAModuleType" "NotAModulePart" @1
		    location   	(217, 155)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(176, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"TestNumber")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC688300B5"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object ModView "Component View::intTest::TestObject" "NotAModuleType" "NotAModulePart" @2
		    location   	(620, 155)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(585, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"TestObject")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC6883006F"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::intTest::TestConst" "NotAModuleType" "NotAModulePart" @3
		    location   	(992, 155)
		    label      	(object ItemLabel
			Parent_View 	@3
			location   	(957, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"TestConst")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC6883000B"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::intTest::intOperator" "NotAModuleType" "NotAModulePart" @4
		    location   	(217, 527)
		    label      	(object ItemLabel
			Parent_View 	@4
			location   	(173, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	162
			label      	"intOperator")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC688203AD"
		    width      	292
		    autoResize 	TRUE
		    width      	292
		    height     	162)
		(object InterfaceView "Logical View::intTest::intOperator" @5
		    location   	(217, 930)
		    label      	(object ItemLabel
			Parent_View 	@5
			location   	(216, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intOperator")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC688203B7"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @6
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF0858016D"
		    client     	@4
		    supplier   	@5
		    line_style 	0)
		(object ModView "Component View::intTest::operable" "NotAModuleType" "NotAModulePart" @7
		    location   	(1023, 527)
		    label      	(object ItemLabel
			Parent_View 	@7
			location   	(988, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"operable")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC68820371"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::intTest::operable" @8
		    location   	(1023, 930)
		    label      	(object ItemLabel
			Parent_View 	@8
			location   	(1022, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"operable")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC68820372"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @9
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF085A0152"
		    client     	@7
		    supplier   	@8
		    line_style 	0)
		(object ModView "Component View::intTest::intTester" "NotAModuleType" "NotAModulePart" @10
		    location   	(651, 527)
		    label      	(object ItemLabel
			Parent_View 	@10
			location   	(616, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"intTester")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC6882032B"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::intTest::intTester" @11
		    location   	(651, 930)
		    label      	(object ItemLabel
			Parent_View 	@11
			location   	(650, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"intTester")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC68820335"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @12
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF085C015F"
		    client     	@10
		    supplier   	@11
		    line_style 	0)
		(object ModView "Component View::intTest::testAble" "NotAModuleType" "NotAModulePart" @13
		    location   	(1333, 527)
		    label      	(object ItemLabel
			Parent_View 	@13
			location   	(1298, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"testAble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC688202C8"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object InterfaceView "Logical View::intTest::testAble" @14
		    location   	(1333, 930)
		    label      	(object ItemLabel
			Parent_View 	@14
			location   	(1332, 1038)
			anchor_loc 	1
			nlines     	2
			max_width  	229
			justify    	0
			label      	"testAble")
		    icon       	"Interface"
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BC688202D1"
		    width      	58
		    height     	58
		    autoResize 	TRUE)
		(object RealizeView "" @15
		    stereotype 	TRUE
		    line_color 	3342489
		    quidu      	"37BF085E00AD"
		    client     	@13
		    supplier   	@14
		    line_style 	0)))))
