package graphic;

import java.awt.Color;
import java.util.Arrays;

/**
 * Implements the Z-Buffer Algorithm.
 * Putting a Pixel also sets an integer z Coordinate.
 * A new Pixel at the same (x,y) Position is only set,
 * when it's z-Value is smaller than the current one.
 *
 * This is nearly a Filter for the Graphics Interface,
 * unfortunately it requires the z Component as a Parameter.
 * The Semantics for the Color has been changed to the z Coordinate.
 * Actually a is be used for the Z-Buffer,
 * because it is not so critical to Overflow!
 * TODO: On the other Hand a short or even Byte Array could also be sufficient 
 * holding the Logarithm of the Distance!   
 *
 * This way all Surfaces and Polygons etc. can be painted in a random Order
 * and even cut through each other. 
 *
 * This Algorithm is similar to Ray- tracing,
 * but the 'Rays' are only traced to the first surface (no Reflexions, no Transparency)
 * and the 'Rays' are not generated by the Algorithm itself.
 *
 * Design Decisions:
 * To avoid the costly indexed Array accesses, 
 * temporary Row and Column Values are kept,
 * which are only updated when the x or y Coordinates change.
 */
final public class ZBuffer
extends AGraph2DOut {

////////////////////////////////////////////////////////////////////////////
/// #region : Variables
////////////////////////////////////////////////////////////////////////////

	/** Switches off updating the Buffer when setting Pixels	 */
	public boolean ignoreBuffer = true;

	/** Maximum Value for x Coordinate */
	protected int XMax;

	/** Maximum Value for y Coordinate */
	protected int YMax;

	/** current Maximum Value for the given x,y Coordinate */
	protected float[][] MinZ;

	/** Cached last X Vector for Optimizations */
	protected float[] X;

	/** Cached last Z Value for Optimizations */
	protected float TmpZ;

	/** Cached last X Value for Optimizations */
	protected int TmpX;

	/** Cached last Y Value for Optimizations */
	protected int TmpY;

	/** Reference to the Delegate */
	protected IGraph2DOut GraphOut;

////////////////////////////////////////////////////////////////////////////
/// #region : Constructors, calling each other using this()/super() (not in Interfaces)
////////////////////////////////////////////////////////////////////////////

	/** Constructor
	 * @param GraphOut_ the Graphics streamIO
	 * @param MaxX the maximum x Coordinate
	 * @param MaxX the maximum y Coordinate
	 */
	public ZBuffer(IGraph2DOut GraphOut_, int MaxX, int MaxY) {
		this.GraphOut = GraphOut_;
		XMax = MaxX;
		YMax = MaxY;
		MinZ = new float[XMax][YMax];
		reset();
	}

////////////////////////////////////////////////////////////////////////////
/// #region : Methods, public ones, then private ones (not in Interfaces)
////////////////////////////////////////////////////////////////////////////

	/**
	 * Resets the Z Buffer.
	 */
	public void reset() {
		if (MinZ == null) 
			return; 
		TmpX = -1;
		TmpY = -1;
		TmpZ = Integer.MAX_VALUE;
		int i = XMax; while (--i >= 0) {
			Arrays.fill(MinZ[i], Integer.MAX_VALUE); } //hopefully faster!
/*			X = MinZ[i];
			int j = YMax; while (--j >= 0) {
				X [j] = Integer.MAX_VALUE; }
		}
*/	}

	/**
	 * Update the temporary Coordinate
	 * with the accumulated temporary minimum z Value
	 * and initialize the new temporary Coordinates x and y .
	 * Usually this happens in the Background when setting Pixels.
	 */
	public void upDate  (int x, int y) {
		if ((x == TmpX) &&
			(y == TmpY)) { return; }
		X[y] = TmpZ; if (x != TmpX) { X = MinZ[x]; }
		TmpZ = X[y];
		TmpX = x;
		TmpY = y;
	}

	/**
	 * SetPixel Routine for the Z-Buffer Algorithm.
	 * Conditionally sets the Pixel and updates the Buffer.
	 * Changing Color only with setColor!
	 */
	public void setPixel (int x, int y, float z) {
		if ((x >= XMax) ||
			(x <  0   ) ||
			(x >= XMax) ||
			(y <  0   )) { return; }
		if (x == TmpX) {
			if (y == TmpY) {
				if (z > TmpZ) { return; }
			} else {
				if (z > X[y]) { return; }
			}
		} else {
			if (z > MinZ[x][y]) { return; } }
		GraphOut.setPixel(x,y);	//Paint the Pixel and update the Coordinates.
		if (ignoreBuffer) { return; }
		if ((x != TmpX) || (y != TmpY)) {
			upDate (x, y); }	//Change the temporary Coordinate
		TmpZ = z;
	}

	////////////////////////////////////////////////////////////////////////////
	/// #region : Interface IGraph2DOut: Implementation
	////////////////////////////////////////////////////////////////////////////
	
	/** Sets the color for the next painting Action */
	public void  setColor(Color color_) { GraphOut.setColor(color_); }

	/**
	 * SetPixel Routine for the Hidden Line Algorithm.
	 * Conditionally sets the Pixel and updates the Buffer.
	 * @see graphic.IGraph2DOut#setPixel(java.awt.Color)
	 */
	public void setPixel(final Color color_) {
		GraphOut.setPixel(P, color_); 
	}
	
}
