/* Generated by Together */

package streamIO.object.parser;

/** This Filter removes Alliterations of Separators.
  * This e.g. applies to WhiteSpace Characters.
  * For improved Functionality it can filter out a range of WhiteSpace Characters.
  * It should be applied as near as possible to the InputStream2StreamIn Object.
  * 
  */
public class AlliterationStreamIn {
}
