
(object Petal
    version    	42
    _written   	"Rose 4.5.8163.3"
    charSet    	0)

(object SubSystem "BodyVectorFuncs"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"37BC8EB90305"
    visible_modules 	(list dependency_list
	(object Dependency_Relationship
	    quid       	"37BC8EB9031B"
	    supplier   	"Component View::intFunction"
	    quidu      	"36BB39470388"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC8EB9031D"
	    supplier   	"Component View::ByRef"
	    quidu      	"36BB4AA503DA"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC8EB9031F"
	    supplier   	"Component View::GroupM"
	    quidu      	"36BB2CD10088"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC8EB90321"
	    supplier   	"Component View::Body"
	    quidu      	"36BB514B0391"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC8EB90323"
	    supplier   	"Component View::Vector"
	    quidu      	"36BB514D0055"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "fSinProd" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\BodyVectorFuncs\\fSinProd.java"))
	    quid       	"37BC8EB90307"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC8EB9031C"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC8EB9031E"
		    supplier   	"Component View::ByRef"
		    quidu      	"36BB4AA503DA"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC8EB90320"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC8EB90322"
		    supplier   	"Component View::Body"
		    quidu      	"36BB514B0391"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC8EB90324"
		    supplier   	"Component View::Vector"
		    quidu      	"36BB514D0055"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1C12015B"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1C12015C"
		    supplier   	"Component View::ByRef"
		    quidu      	"36BB4AA503DA"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1C120163"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1C120164"
		    supplier   	"Component View::Body"
		    quidu      	"36BB514B0391"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD1C120165"
		    supplier   	"Component View::Vector"
		    quidu      	"36BB514D0055"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD361C028D"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD361C028E"
		    supplier   	"Component View::ByRef"
		    quidu      	"36BB4AA503DA"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD361C028F"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD361C0295"
		    supplier   	"Component View::Body"
		    quidu      	"36BB514B0391"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD361C0296"
		    supplier   	"Component View::Vector"
		    quidu      	"36BB514D0055"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "BodyVectorFuncs"
	    quid       	"37BF0A0A0095"
	    title      	"BodyVectorFuncs"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::BodyVectorFuncs::fSinProd" "NotAModuleType" "NotAModulePart" @1
		    location   	(310, 186)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(275, 161)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fSinProd")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC8EB90307"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)))))
