package function.derive.ring.body.vector;

import streamIO.copy.group.ring.IIntRing;
import streamIO.copy.group.ring.metric.IMetricIRing;
import streamIO.copy.group.ring.metric.body.vector.Tensor;
import function.AFunction;

/**This Class encapsulates the the Charge Field Function,
 * resulting from the Poisson Equation, in arbitrary Dimensions.
 * Because except for a constant Factor this is the Green Function
 * for the Poisson Equastion: phi(r) = 1/r => y[i] = -y[i]/r^3
 * , it returns the Force Field Vector generated by the Point Charges.
 *
 * The given Coordinates are examples for simple MultiPoles
 * to generate MultiPole Moments: M(Order) =  Sum (c[m]*r[m]^Order) = M[i,j,k,...].
 * The linear Versions of the QuadruPole and OctoPole are simply denaturated Versions
 * of their planar counterparts.
 * To define a Multipol of higher order you need three Dimensions.
 * All Multipoles have their center of Charge in the Origin of the Coordinate System.
 * The MultiPole Moments of lesser Order are Zero with these Examples, i.e.
 * MultiPoles of Order > 0 (MonoPole) are electrically neutral etc.
 * The MultiPole Moments of higher Order are not Zero with these Examples,
 * because the MultiPoles have an extent!	*/
public class fChargeField
extends AFunction {

	/**Square Root of 1/2 = 0.7172..., needed for the Coordinates of the MultiPoles	 */
	final static public double SqRtHalf = Math.sqrt(0.5);

	/**Coordinates for a pure MonoPol, i.e. one Charge Unit
	 * in the Center of the Coordinate System	 */
	final static public double [][] MonoPol = {{0}};

	/**Coordinates for a pure DiPol along the x Axis with a Distance of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] DiPol	= {{-1}, {+1}};

	/**Coordinates for a pure planar QuadruPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] QuadPol = {	DiPol  [0],	DiPol  [1],	{0, -1},{0, +1}};

	/**Coordinates for a pure linear QuadruPol on in the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] lQuadPol= {	DiPol  [0],	MonoPol  [0], DiPol  [1]};

	/**Coordinates for a pure planar OctoPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] OctoPol = {	QuadPol[0], QuadPol[1], QuadPol[2], QuadPol[3],
												{+SqRtHalf,+SqRtHalf}, {+SqRtHalf,-SqRtHalf},
												{-SqRtHalf,+SqRtHalf}, {-SqRtHalf,-SqRtHalf}};

	/**Coordinates for a pure linear OctoPol on the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [][] lOctoPol= {	DiPol [0], {-SqRtHalf}, MonoPol[0], {+SqRtHalf}, DiPol [1]};


	/**Charges for a pure MonoPol, i.e. one Charge Unit in the Center of the Coordinate System	 */
	final static public double [] cMonoPol = {1};

	/**Charges for a pure DiPol along the x Axis with a Distance of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] cDiPol	= {-1, +1};

	/**Charges for a pure linear QuadruPol on in the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] clQuadPol= {+1, -2, +1};

	/**Charges for a pure planar QuadruPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] cQuadPol = {+1, +1, -1, -1};

	/**Charges for a pure planar OctoPol in the x/y Plane with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] cOctoPol = {	+1, +1, +1, +1,
												-1, -1, -1, -1};

	/**Charges for a pure linear OctoPol on the x Axis with a Diameter of 2
	 * in the Center of the Coordinate System	 */
	final static public double [] clOctoPol= {	+1, -2, +2, -2, +1};

	/**Number of Charges	 */
	protected int numCharges;

	/**Positions of the Charges	 */
	protected Tensor[] Points;

	/**relative Position of the current Charge	 */
	protected Tensor Dist;

	/**Amounts of the Charges	 */
	protected IIntRing[] Charges;

	/**Constructor that takes the Charges and it's Coordinates.
	 * The Charges are not integrated into the Vectors as n+1 Dimension,
	 * because the Vectors wouldn't transform correctly anymore!	 */
	public fChargeField(final Tensor[] Points, final IIntRing[] Charges) {
		if ((numCharges = Charges.length) != Points.length) throw new AbstractMethodError();
		this.Points  = Points;
		this.Charges = Charges;
		Dist = new Tensor(); //Points[0].Carry);
	}

	/**This Function represents the Charge Field Function.
	 * It returns the Force Field Vector generated by the Charges.  */
	public Object Map(final Object arg) {
		Tensor y = new Tensor(); //Dist.Carry);	//saves adding the first Vector,
		int i = -1;					//since it is recoginzed that this Tensor is empty!
		while (++i < numCharges) {	//transform it to a Coordinate System with Points[i] in the Origin
			((Tensor) Dist.copyAt(arg)).subAt(Points[i]);
//			Dist = ((Tensor) arg).subt(Points[i]);
			IMetricIRing dist = Dist.SqrNorm();
			y.addProdAt(Charges[i].div(dist.mulAt(dist.SqRt())), Dist);
		}
		return y; }

}
