/*
 * Created on 18.04.2003
 *
 * To change the template for this generated file go to
 * Window>Preferences>Java>Code Generation>Code and Comments
 */
package streamIO.real;

import streamIO.AReSetAble;
import streamIO.IReSetAble;
import streamIO.integer.random.IStreamIn_Bound_Int;
import streamIO.integer.random.RandomFast;
import streamIO.real.random.TestRandom;
import function.IFloatFunction;
import function.byref.combinatoric.ProbFuncs;
import function.derive.ring.body.Logarithm;
import function.derive.ring.body.Tangens;
import function.real.BiLinearSum;
import function.real.Multiplier;
import function.real.Sum;

/**
 * Implements a filter over a float random-number stream that optionally maps each value
 * through an {@link IFloatFunction} before delivery.
 *
 * <p>Implements a filter for Random Numbers
 * and optionally applies a mapping Function to the incoming Numbers 
 * 
 * Known SubClasses: 
 * @see streamIO.real.random.RandomLorentz
 *
 * Known Uses: <none>
 *
 * Copyright:	Copyright (c) Matthias Heuer<p>
 * Company:	personal<p>
 * Created on	10-26-2002, 12:47 PM<p>
 * @author mheuer
 * @version	1.0
 *
 * <!-- docstate
 * pass: 2
 * mtime: 2026-09-05T11:18:52Z
 * digest: 06ac6ca3c9d658e4c9ddba639b6eea6afa2b99418f9950d89eb96e74d5be995b
 * stale: false
 * tags: [code/stream_filter]
 * concepts: [Function-Based Float Input Filter]
 * facets: {layer: infrastructure, status: legacy, complexity: low}
 * -->
 */
public class FilterIn_FloatByFunction 
extends AStreamIn_Float {
	
	///////////////////////////////////////////////////////////////////////////////////////
	//	static Methods
	///////////////////////////////////////////////////////////////////////////////////////

	/** Shared, process-wide exponentially distributed random stream, seeded from {@link RandomFast#RANDOM}. */
	final static public IStreamIn_Float RANDOM_EXPONENTIAL = RANDOM_EXPONENTIAL((IStreamIn_Bound_Int) RandomFast.RANDOM);

	/** Draws the next value from the shared {@link #RANDOM_EXPONENTIAL} stream.
	 * @return a Number distributed with p(x) = exp(-x)	 */
	final static public double RANDOM_DOUBLE_EXPONENTIAL() {
		return RANDOM_EXPONENTIAL.nextDouble();
	}

	/** Draws the next value from the shared {@link #RANDOM_EXPONENTIAL} stream.
	 * @return a Number distributed with p(x) = exp(-x)	 */
	final static public float RANDOM_FLOAT_EXPONENTIAL() {
		return RANDOM_EXPONENTIAL.nextFloat();
	}
	
	/** Returns random negative Numbers distributed in an exponential fashion,
	  * i.e. p(x) = exp(-x)
	  * Changing the Sign is left to the Application to increase Performance!
	  * These Values usually occur as waiting times T = ran()
	  * between independent Events distributed in a Poisson fashion,
	  * e.g. the Decay of Nuclei with the Lifetime 1.
	  * For other lifetimes L the Waiting times just scale: T'=L*ran()
	  *
	  * The Distribution can be scaled by a (positive) Factor m, but not translated.
	  * The Values must be negated, since they are always negative.
	  *
	  * With m = 1/Ln(p) negative, the integer Part of the Distribution
	  * describes a geometric Distribution:
	  * Geo() = 1+Floor(ln(Ran())/ln(p))
	  */
	final static public IStreamIn_Float RANDOM_EXPONENTIAL(final IStreamIn_Float stream) {
		return new FilterIn_FloatByFunction(stream, Logarithm.LOGARITHM);
	}
	
	/** Returns random negative Numbers distributed in an exponential fashion,
	  * i.e. p(x) = exp(-x)
	  * Changing the Sign is left to the Application to increase Performance!
	  * These Values usually occur as waiting times T = ran()
	  * between independent Events distributed in a Poisson fashion,
	  * e.g. the Decay of Nuclei with the Lifetime 1.
	  * For other lifetimes L the Waiting times just scale: T'=L*ran()
	  *
	  * The Distribution can be scaled by a (positive) Factor m, but not translated.
	  * The Values must be negated, since they are always negative.
	  *
	  * With m = 1/Ln(p) negative, the integer Part of the Distribution
	  * describes a geometric Distribution:
	  * Geo() = 1+Floor(ln(Ran())/ln(p))
	  */
	final static public IStreamIn_Float RANDOM_EXPONENTIAL(final IStreamIn_Bound_Int stream) {
		return new FilterIn_FloatByFunction(new FilterInMul(stream, 1.0), //for scaling the Values between 0 and 1
			Logarithm.LOGARITHM);
	}
	
	/**Returns random Numbers distributed in a Lorentz fashion
	 * i.e. p(x) = 1/Pi*(1 + x^2)
	 * These Values represent a Value centered around 0 with a Deviation of 1
	 * Any other Distributions can easily be generated by affine Transformation:
	 * For Center b with Standard Deviation a:
	 * ran(a,b) = a*ran() + b	=> p(a,b,x) ~ 1/(a^2 + (x-b)^2)
	 *
	 * This Distribution is fuzzily distributed around x0.
	 * The Probability of Values lying away from Center b falls inversely: 1/x.
	 * This Distribution is e.g. used as a comparison Function
	 * for the Rejection Method.
	 */
	final static public IStreamIn_Float RANDOM_LORENTZ(final IStreamIn_Float stream) {
		return 
			new FilterIn_FloatByFunction(
			new FilterIn_FloatByFunction(stream,
			new Multiplier(Math.PI)), //for scaling the Values between 0 and PI
			Tangens.TANGENS);
	}
	
	/**Returns random Numbers distributed in a Lorentz fashion
	 * i.e. p(x) = 1/Pi*(1 + x^2)
	 * These Values represent a Value centered around 0 with a Deviation of 1
	 * Any other Distributions can easily be generated by affine Transformation:
	 * For Center b with Standard Deviation a:
	 * ran(a,b) = a*ran() + b	=> p(a,b,x) ~ 1/(a^2 + (x-b)^2)
	 *
	 * This Distribution is fuzzily distributed around x0.
	 * The Probability of Values lying away from Center b falls inversely: 1/x.
	 * This Distribution is e.g. used as a comparison Function
	 * for the Rejection Method.
	 * 
	 * @see streamIO.real.random.RandomLorentz for an alternative, faster Implementation
	 */
	final static public IStreamIn_Float RANDOM_LORENTZ(final IStreamIn_Bound_Int stream) {
		return 
			new FilterIn_FloatByFunction(
			new FilterInMul(stream, Math.PI), //for scaling the Values between 0 and PI
			Tangens.TANGENS);
	}
	
	/** Generates random Numbers with a Lorentz Noise Spectrum,
		 * i.e. the Power falls like 1/(1 + f*f)
		 *
		 * A uniform Random Noise Generator also generates a uniform
		 * Power Spectrum (heuristic Reason: Spectrum is as random!)
		 * Since P(0) = Infinity, the Signal Value could exceed any Bound.
		 *
		 * This Spectrum is limited in f(0), so it cannot walk off arbitrarily.
		 *
		 * @return a Noise Generator with a Lorentz Shape Spectrum, 
		 * assuming the given streamIO is a White Noise Generator, 
		 * which should be scaled around 0 to remove linear Trends. 
		 */
	final static public IStreamIn_Float LORENTZ_NOISE(
		final IStreamIn_Float stream,
		final double fGrenz,
		final double Seed,
		final double Scale) {
		return new FilterIn_FloatByFunction(stream,
		//new LinearScale(-IMeasurAble.HALF, +IMeasurAble.HALF)); //for scaling the Noise to 0 and thus removing linear Trends
		new BiLinearSum(fGrenz, Seed, Scale));
	}

	/**Generates random Numbers with a brown Noise Spectrum,
		 * i.e. the Power falls like f^-2 = 1/(f*f)
		 *
		 * A uniform "White" Random Noise Generator also generates a uniform
		 * Power Spectrum (heuristic Reason: Spectrum is as random as the Values!)
		 * Since P(0) = Infinity, the Signal Value could exceed any Bound.
		 *
		 * This discrete Transformation brown[i] = white[i] + brown[i-1]
		 * results in a 1/(f*f) Filter Operation.
		 *
		 * This corresponds to a 1-dim random Walk.
		 * It is proven that the Probability to reach a certain Value x
		 * p(x) = 1 for any x at any Time,
		 * but at the same Time the Probability to reach this Value consistently
		 * within a certain Number of Samples is 0.
		 *
		 * Interestingly the Probability to reach a certain Position
		 * (e.g. the Start Point, but as likely any other Point) in an infinite Sample
		 * depends on the Dimension of the Space traversed:
		 * Dimension   : 1   2   3    4
		 * p(certain X): 1   1  0,34 0.19
		 *
		 * Similarly the Probability for all Sides of a Dice with N Sides
		 * to appear with an equal Number is:
		 * N:    1 2 3   4     5
		 * p(N): 1 1 1 0,222 0,066
		 *
		 * But this Result only emphasizes that there is no 'Tendency'
		 * to reach the Start Value at any Time, only the a priori Probability is low.
		 * Similarly the Probability that in the accumulated Result both Numbers
		 * appear equally often approaches 0.
		 * The most probable Results are: 0 leads all the Time or 1 leads all the Time
		 * The Rest is made up of the Probabilities for Ratios of 0s to 1s.
		 *
		 * It all depends on the Sample Size:
		 * With an infinite Sample the Probability of any Event is 1
		 * With a    finite Sample the Probability of these Events can be anything from 0 to 1:
		 * a possible Event can approach 0 in a finite Sample (Likelihood)
		 * or it approaches any other Value between 0 and 1,
		 * because the Probability to happen in a finite Sample can be calculated
		 * from the individual Probabilities.
		 *
		 * E.g. the Probability for a certain Sequence like 00010110 is 1/256,
		 * just like any other Sequence, but the Probability of the Ratio of 3*1s
		 * to 5*0s neglects the Sequence and thus is 8!/(3!*5!*256) = 56/256 = 2/9
		 * Similar Calculations hold for the Occurrence of Sub-Sequences in longer Samples.
		 *
		 * @return a Brown Noise Generator, 
		 * assuming the given streamIO is a White Noise Generator, 
		 * which should be scaled around 0 to remove linear Trends. 
		 */
	final static public IStreamIn_Float BROWN_NOISE(
			final IStreamIn_Float stream,
			final double startValue_) {
		return new FilterIn_FloatByFunction(stream,
		//		new LinearScale(-IMeasurAble.HALF, +IMeasurAble.HALF)); //for scaling the Noise to 0 and thus removing linear Trends
		new Sum(startValue_));
	}
	
	///////////////////////////////////////////////////////////////////////////////////////
	//	Member Variables 
	///////////////////////////////////////////////////////////////////////////////////////
	
	/** Local Reference to the Generator	 */
	protected final IStreamIn_Float inStream;
	
	/** the actual stateful Mapping Function;  
	 * if null, the Identical Mapping is performed. 
	 */
	protected final IFloatFunction mapper;
	
	///////////////////////////////////////////////////////////////////////////////////////
	//	Constructors
	///////////////////////////////////////////////////////////////////////////////////////
	
	/** Initializing Constructor
	  * @param Generator the actual IStreamInNumber
	  * @param Scale     Maximum Value returned by this Filter */
	public FilterIn_FloatByFunction(final IStreamIn_Float InStream_) {
		this(InStream_, null); }
	
	/** Initializing Constructor
	  * @param Generator the actual IStreamInNumber
	  * @param Scale     Maximum Value returned by this Filter */
	public FilterIn_FloatByFunction(final IStreamIn_Float InStream_, final IFloatFunction mapper_) {
		mapper = mapper_; this.inStream = InStream_; }
	
	///////////////////////////////////////////////////////////////////////////////////////
	//	Read/Write for Count
	///////////////////////////////////////////////////////////////////////////////////////

	/** Cache for the Count, publicly accessible,
	 * because never out of synch, except during an Operation.	*/
	protected long count;

	/** Returns the current count of all elements passed through this filter.
	 * @return the current Count of all Elements	*/
	public long getCount() { return count; }

	/** sets the current Count of all Elements	*/
	public void setCount(long Count_) {
		this.count = Count_; }

	///////////////////////////////////////////////////////////////////////////////////////
	//	Interface IStreamIn_Float
	///////////////////////////////////////////////////////////////////////////////////////

	/** Attempts to reset the wrapped stream, falling back to a no-op if it is not resettable.
	 * @see streamIO.integer.IStreamIn_Int#reSet()	 */
	public IReSetAble reSet() { //throws IOException {
		return AReSetAble.TRY_TO_RESET(inStream, FilterIn_FloatByFunction.class.toString());
	}

	/** Applies this filter's mapping function to a double value, or returns it unchanged if none is set.
	 * @return the double Precision arg, mapped by the given Function	 */
	final public double map(final double arg) {
		if (mapper == null)
			return arg;
		return mapper.Map(arg);
	}

	/** Applies this filter's mapping function to a float value, or returns it unchanged if none is set.
	 * @return the single Precision arg, mapped by the given Function	 */
	final public float map(final float arg) {
		if (mapper == null)
			return arg;
		return mapper.Map(arg);
	}

	/** Returns the maximum mark size of the wrapped stream.
	 * @see streamIO.object.AStreamIn#getMaxMarkSize()	 */
	public long getMaxMarkSize() { return inStream.getMaxMarkSize(); }

	/** Returns the current position of the wrapped stream.
	 * @see streamIO.object.AStreamIn#getPosition()	 */
	public long getPosition() { return inStream.getPosition(); }

	/** Returns the number of items still available from the wrapped stream.
	 * @see streamIO.real.AAStreamIn_Float#availAble()	 */
	public long availAble() { return inStream.availAble(); }

	/** Reads and maps the next float value from the wrapped stream.
	 * @return the next single Precision Number	 */
	public float nextFloat() { final float ret;
		currItem.Value = ret = map(inStream.nextFloat());
		return ret; }

	/** Reads and maps the next double value from the wrapped stream.
	 * @return the next double Precision Number	 */
	protected double nextDoubleInternal() { return map(inStream.nextDouble()); }
	
	///////////////////////////////////////////////////////////////////////////////////////
	//	Interface IStreamIn_Bound_Int
	///////////////////////////////////////////////////////////////////////////////////////

	/** Returns the sort order of the wrapped stream.
	 * @return the Order in which Elements are returned by the Iterators
		  * when they are added using addItem() and removed using nextItem().	 */
	public byte getOrder() { return inStream.getOrder(); }

	/** Returns the mapped minimum value producible by the wrapped generator.
	 * @return the minimum Value for other Classes to determine.
	 * Assumes that the Mapping is monotonusly and rising.
	 */
	public double getMinDouble() { return map(((IStreamIn_Bound_Int) inStream).getMinValue()); }

	/** randomizes this Generator 	 */
	//public void randomize() { ((IStreamIn_Bound_Int) inStream).randomize(); }

	/** Returns the mapped maximum value producible by the wrapped generator.
	 * @return the maximum Value for other Classes to determine.
	 * Assumes that the Mapping is monotonusly and rising.
	 */
	public double getMaxDouble() { return map(((IStreamIn_Bound_Int) inStream).getMaxValue()); }

	/////////////////////////////////////////////////////////////////////////////////////

	/**Tests the Exponential Random Number Generator	 */
	final static public void testExponential
	(final IStreamIn_Bound_Int ran
	, final double scale, final float shift, final int NPTS, final int numBins) {
		final float[] compare = new float[numBins];
		for (int i = numBins; --i >= 0;) { 
			compare[i] = (float) -(ProbFuncs.pExp((shift-.5 - i)*scale)*scale); } 
		TestRandom.TEST_RANDOM(FilterIn_FloatByFunction.RANDOM_EXPONENTIAL(ran), compare, scale, numBins, shift, NPTS, "Exponential");
	}

}
