package knowledge;

/**
  * Gives an object a human-readable name and description.
  *
  * <p>The two {@code STR_} constants are the column and field names those two properties
  * are stored under, exposed here so persistence code names them once rather than
  * repeating string literals.
  * <!-- docstate
  * pass: 2
  * mtime: 2026-09-05T08:08:18Z
  * digest: fa851efe1fb3361d5f2a89597fc80163781a5806062d7de484091002c9aae71e
  * stale: false
  * -->
  */
public interface IDescriptor {

	//////////////////////
	//  static Members  //
	//////////////////////
	
	/** String Constant  */
	final static public String STR_Name = "Name"; 
	
	/** String Constant  */
	final static public String STR_Description = "Description"; 
	
	///////////////
	//  Methods  //
	///////////////

	/** Returns the unique ID for this Object.
	 *  Generated by AutoNumber / Sequence in the DB */
//	public int getID();

	/** Returns the Name for this Object. */
	String getName();

	/** Returns the Description of this Object. */
	String getDescription();

}
