package knowledge;

/**
  * Defines Methods for an Object that contains a Name and a Description
  */
public interface IDescriptor {

	//////////////////////
	//  static Members  //
	//////////////////////
	
	/** String Constant  */
	final static public String STR_Name = "Name"; 
	
	/** String Constant  */
	final static public String STR_Description = "Description"; 
	
	///////////////
	//  Methods  //
	///////////////

	/** Returns the unique ID for this Object.
	 *  Generated by AutoNumber / Sequence in the DB */
//	public int getID();

	/** Returns the Name for this Object. */
	String getName();

	/** Returns the Description of this Object. */
	String getDescription();

}
