package knowledge;

import java.lang.reflect.Field;


/**
  * IdKey.java
  *
  * Created on 9. Mai 2001, 00:01
  *
  * Primary key for an ID Based Class
  * The Reason to use IDs with no Meaning at all is to have a stable Identifier.
  *
  * Subclasses:
  * @see knowledge.Status
  *
  *
  * @author  Matthias Heuer
  * @version
  */
public class IdKey
extends DirtyFlag
implements PersistAble, IPrimaryKey {

	////////////////////////////////////////////////////////////////////////////
	//  static Members
	////////////////////////////////////////////////////////////////////////////

	/** String Constant  */
//	final static public String STR_ID = "ID";

	/** Array of key Field Names,
	  * conCat selects only the non static, final or transient Fields	 */
	final static public Field[] Keys = DBObjectFactory.conCat(new Field[0], IdKey.class.getDeclaredFields()); //

	/** Array of Class Objects for determining the correct Constructor
	  * on dynamically creating new Instances.  */
	final static public Class[] KeyTypes = DBObjectFactory.getFieldTypes(Keys);

	/** String Constants for the Object Field Names */
	final static public String[] KeyNames = DBObjectFactory.getFieldNames(Keys);

	/** String Constants for the DB Field Names */
	final static public String[] DBKeyNames = KeyNames;

	////////////////////////////////////////////////////////////////////////////
	//  static Methods
	////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////
	//  Members
	////////////////////////////////////////////////////////////////////////////

	/** Unique ID for this Status. Generated by AutoNumber / Sequence in the DB */
	protected int ID;

	////////////////////////////////////////////////////////////////////////////
	//  Accessors
	////////////////////////////////////////////////////////////////////////////

	/** Unique ID for this Status. Generated by AutoNumber / Sequence in the DB */
	public int getID() { return ID; }

	////////////////////////////////////////////////////////////////////////////
	//  Constructors
	////////////////////////////////////////////////////////////////////////////

	/** Empty Constructor for Subclasses */
//	protected IdKey() {}

    /** Creates new IdKey */
    public IdKey (int ID) { this.ID = ID; }

	/** key Constructor for a Status, needs to be initialized from the DB */
	public IdKey(Integer ID) { this(ID.intValue()); }

	/** Overloaded Constructor initializing by the primary key 	  */
	public IdKey(IPrimaryKey Key) { if (Key != null) this.ID = ((IdKey) Key).ID; }

	////////////////////////////////////////////////////////////////////////////
	//  Methods
	////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////
	//	Interface Object
	////////////////////////////////////////////////////////////////////////////

	/** Returns a String representing this Object, here the SQL Condition is chosen.
	  * This generic Implementation can be overridden by faster hardcoded ones. */
	public String toString() { return Condition(); }

	/**  Returns a hashcode for this Object
	 *  This HashCode has to be identified with the primary key of this Object  */
	public int hashCode() { return ID; }

	/** Compares this object to the specified object.
	 *  This Comparison has to be compliant with the primary key of this Object  */
	public boolean equals(Object obj) {
		if (obj == this) return true;
		if (! (obj instanceof IdKey)) return false;
		return ((IdKey)obj).ID == this.ID; }

	////////////////////////////////////////////////////////////////////////////
	//	Interface IPrimaryKey
	////////////////////////////////////////////////////////////////////////////

	/** Array of the Field Objects for this Class, including Parent Fields */
	public Field[] Keys() { return Keys; }

	/** String Constants for the Field Names */
	public String[] KeyNames() { return KeyNames; }

	/** String Constants for the DBField Names */
	public String[] DBKeyNames() { return DBKeyNames; }

	/** Returns a String representing the SQL Condition for this Primary key
	  * This generic Implementation can be overridden by faster hardcoded ones. */
	public String Condition () { return DBObjectFactory.Condition(this, ""); }

	////////////////////////////////////////////////////////////////////////////
	//	Interface PersistAble
	////////////////////////////////////////////////////////////////////////////

	/** Overloaded Constructor initializing to the Primary key	  */
/*	public IPrimaryKey newInstance (IPrimaryKey Key) throws SQLException {
		return new IdKey(((IdKey)Key).ID); }
//		return (IPrimaryKey) newInstance(new IdKey(RS.getInt(DBKeyNames[0]))); } //since there is only one Field, Sequence doesn't matter here!

	/** Overloaded Constructor initializing by the primary Key 	  */
	public PersistAble newInstance (IPrimaryKey Key) {
		return DBObjectFactory.newInstance (this, Key); }

	/** DB Table Name for this Class  */
	public String TableName () { return ""; }

	/** Array of the Field Objects for this Class, including Parent Fields  */
	public Field[] Fields () { return Keys; }

	/** String Constants for the Field Names  */
	public String[] FieldNames () { return KeyNames; }

	/** String Constants for the DBField Names  */
	public String[] DBFieldNames () { return DBKeyNames; }

	/** Returns an Object representing the Primary key
	 * Not really necessary: usually the Object itself represents it's primary key  */
	public IPrimaryKey primaryKey () { return this; }

	/** Returns the foreign key Condition,
	 * i.e. the Condition for Objects holding a foreign key to this Object,
	 * but only for standard Naming: i.e. "<TableName>ID",
	 * which is not sufficient for e.g. parallel Relations.  */
	public String ForeignKeyCondition () { return null; }

	/** Array of Class Objects for the Constructor	  */
	public Class[] KeyTypes () { return KeyTypes; }
}
