package knowledge;

import java.lang.reflect.Field;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/** Describes the List of available Statuses for most Objects in this Package.
  *  Also Base Class for most Objects in this Package.
  *
  * Subclasses:
  * @see knowledge.MetaType
  *
  */
public class Status
extends IdKey 
implements PersistAble, IDescriptor { //, IPersistAble {
	
	////////////////////////////////////////////////////////////////////////////
	//  static Members  
	////////////////////////////////////////////////////////////////////////////
	
	/** String Constant for the Table Name */
	final static public String STR_TableName = "Status"; //Status.class.getName();// 
	
	/** String Constant for the Field Names */
//	final static public String STR_FieldNames = "Name, Description "; 
	
	/** Array of Field Names, selects only the non static, final or transient Fields
	  * The key is left out by Construction */
	final static public Field[] Fields = DBObjectFactory.conCat(new Field[0], Status.class.getDeclaredFields()); //getFields ()};
	
	/** String Constants for the Field Names */
	final static public String[] FieldNames = DBObjectFactory.getFieldNames(Fields);
	
	/** String Constants for the DBField Names */
	final static public String[] DBFieldNames = FieldNames;
	
	////////////////////////////////////////////////////////////////////////////
	//  static Methods  
	////////////////////////////////////////////////////////////////////////////
	
	////////////////////////////////////////////////////////////////////////////
	//  Members  
	////////////////////////////////////////////////////////////////////////////
	
	/** A descriptive Name for this Status, need not be unique.
	 *  Not implemented as an Attribute to have a least Common Denominator.
	 */
	protected String Name;
	
	/** A Description of this Status. 	 */
	protected String Description;
	
	/** Reference to the Statement used for executing SQL Commands. 	 */
	public Statement StateMt;
	
	////////////////////////////////////////////////////////////////////////////
	//  Accessors  
	////////////////////////////////////////////////////////////////////////////
	
	/** A Name for this Status.
	 *  A descriptive Name for this Object, need not be unique.
	 *  Not implemented as an Attribute to have a least Common Denominator.
	 */
	public String getName() { return Name; }
	
	/** A Description of this Status. 	 */
	public String getDescription() { return Description; }
	
	/** A Name for this Status.
	 *  A descriptive Name for this Object, need not be unique.
	 *  Not implemented as an Attribute to have a least Common Denominator.
	 */
	public void setName(String Name) { dirty = true; this.Name = Name; }
	
	/** A Description of this Status. 	 */
	public void setDescription(String Description) { dirty = true; this.Description = Description; }
	
	////////////////////////////////////////////////////////////////////////////
	//  Constructors 
	////////////////////////////////////////////////////////////////////////////
	
	/** Empty Constructor for Subclasses */
//	protected Status() {}
	
	/** Primary key Constructor */
	public Status(IPrimaryKey Key) { super(Key); }
	
	/** key Constructor for a Status, needs to be initialized from the DB */
	public Status(int ID) { super(ID); } 
	
	/** key Constructor for a Status, needs to be initialized from the DB */
	public Status(Integer ID) { super(ID); } 
	
	/** Full Constructor for a Status */
	public Status(int ID, String Name, String Description) {
		super(ID); 
		this.Name = Name; 
		this.Description = Description; 
	}
	
	////////////////////////////////////////////////////////////////////////////
	//  Methods  
	////////////////////////////////////////////////////////////////////////////
	
	/**  On Destruction these Objects have to update the DB! */
	public void finalize() {
		if (ID == 0) {
            //TODO:
            //check whether to Update or to Insert, can be saved...
			//Convention: 0 means new, positive means Update, negative means Delete
			//the Sequence can be generated by this Class, not only the DB!
		} else {
		}
//		super.finalize();
	}
	
	/** Returns the foreign key Condition for the Table determined by the Factory, 
	  * i.e. the Condition for Objects holding a foreign key to this Object, 
	  * but only for standard Naming: i.e. "<TableName>ID", 
	  * which is not sufficient for e.g. parallel Relations. */
	public ArrayList relatedObjects(DBObjectFactory FactoryObject) throws SQLException {
		return FactoryObject.getObjects(ForeignKeyCondition()); }
	
	////////////////////////////////////////////////////////////////////////////
	//	Interface PersistAble
	////////////////////////////////////////////////////////////////////////////
	
	/** DB Table Name for this Class */
	public String TableName() { return STR_TableName; }
	
	/** Array of the Field Objects for this Class, including Parent Fields */
	public Field[] Fields() { return Fields; }
	
	/** String Constants for the Field Names */
	public String[] FieldNames() { return FieldNames; }
	
	/** String Constants for the DBField Names */
	public String[] DBFieldNames() { return DBFieldNames; }
	
	/** Returns the foreign key Condition, 
	  * i.e. the Condition for Objects holding a foreign key to this Object, 
	  * but only for standard Naming: i.e. "<TableName>ID", 
	  * which is not sufficient for e.g. parallel Relations. */
	public String ForeignKeyCondition() { 
		return DBObjectFactory.Condition(this, TableName()); } 
	
}
