
(object Petal
    version    	42
    _written   	"Rose 4.5.8163.3"
    charSet    	0)

(object SubSystem "GroupM"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"36BB2CD10088"
    visible_modules 	(list dependency_list
	(object Dependency_Relationship
	    quid       	"37BFD84C02C0"
	    supplier   	"Component View::BaseCopy"
	    quidu      	"36BABF4B0011"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "HalfGroupM" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\GroupM\\HalfGroupM.java"))
	    quid       	"36BB2CD101AA"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB2D840040"
		    supplier   	"Component View::BaseCopy::copyAble"
		    quidu      	"36BABF500108"
		    supplier_is_spec 	TRUE))
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF01B00054"
		    supplier   	"Logical View::GroupM::HalfGroupM"
		    quidu      	"36BB2CD101B4"))
	    language   	"Java")
	(object module "absHalfGroupM" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\GroupM\\absHalfGroupM.java"))
	    quid       	"36BB2CD10254"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BBFB7100C6"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC919503BC"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD20360013"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD380900D1"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "GroupM" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\GroupM\\GroupM.java"))
	    quid       	"36BB2CD102AF"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF01A902D5"
		    supplier   	"Logical View::GroupM::GroupM"
		    quidu      	"36BB2CD102B9"))
	    language   	"Java")
	(object module "absGroupM" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\GroupM\\absGroupM.java"))
	    quid       	"36BB2CD20011"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"36BB2D84025C"
		    supplier   	"Component View::BaseCopy::copyAble"
		    quidu      	"36BABF500108"
		    supplier_is_spec 	TRUE))
	    language   	"Java")
	(object module "testGroupM" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\GroupM\\testGroupM.java"))
	    quid       	"37BC919700EE"
	    stereotype 	""
	    language   	"Java")
	(object module "intGroupM" "NotAModuleType" "NotAModulePart"
	    quid       	"37BF536E0069"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF541C011D"
		    supplier   	"Logical View::GroupM::intGroupM"
		    quidu      	"36BB2CD10146"))
	    language   	"Java")
	(object module "intHalfGroupM" "NotAModuleType" "NotAModulePart"
	    quid       	"37BF53870046"
	    stereotype 	""
	    realized_interfaces 	(list realize_rel_list
		(object Realize_Relationship
		    quid       	"37BF54C60352"
		    supplier   	"Logical View::GroupM::intHalfGroupM"
		    quidu      	"36BB2CD100BA"))
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "GroupM"
	    quid       	"37BF019D033C"
	    title      	"GroupM"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::GroupM::testGroupM" "NotAModuleType" "NotAModulePart" @1
		    location   	(217, 155)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(176, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"testGroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC919700EE"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object ModView "Component View::GroupM::absGroupM" "NotAModuleType" "NotAModulePart" @2
		    location   	(651, 155)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(610, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"absGroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB2CD20011"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object ModView "Component View::GroupM::GroupM" "NotAModuleType" "NotAModulePart" @3
		    location   	(186, 527)
		    label      	(object ItemLabel
			Parent_View 	@3
			location   	(151, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"GroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB2CD102AF"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::GroupM::absHalfGroupM" "NotAModuleType" "NotAModulePart" @4
		    location   	(1085, 155)
		    label      	(object ItemLabel
			Parent_View 	@4
			location   	(1038, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	174
			label      	"absHalfGroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB2CD10254"
		    width      	314
		    autoResize 	TRUE
		    width      	314
		    height     	162)
		(object ModView "Component View::GroupM::HalfGroupM" "NotAModuleType" "NotAModulePart" @5
		    location   	(589, 527)
		    label      	(object ItemLabel
			Parent_View 	@5
			location   	(548, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"HalfGroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"36BB2CD101AA"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object ModView "Component View::GroupM::intGroupM" "NotAModuleType" "NotAModulePart" @6
		    location   	(1023, 527)
		    label      	(object ItemLabel
			Parent_View 	@6
			location   	(982, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"intGroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BF536E0069"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)
		(object ModView "Component View::GroupM::intHalfGroupM" "NotAModuleType" "NotAModulePart" @7
		    location   	(1395, 527)
		    label      	(object ItemLabel
			Parent_View 	@7
			location   	(1354, 502)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	150
			label      	"intHalfGroupM")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BF53870046"
		    width      	270
		    autoResize 	TRUE
		    width      	270
		    height     	162)))))
