package streamIO.object.integer;

import graphs.KeyValuePair;

import java.io.IOException;
import java.io.InputStream;
import java.io.StringBufferInputStream;

import streamIO.object.AStreamIn;

/**This Class is an Engine to the Event Based Interface from the XMLScanner
 * to Streams carrying SGML.
 * The Portion of the XML Grammar that doesn't deal with individual Tags,
 * but with complete XML Elements is reflected here.
 *
 * Returns a streamIO of XML Elements.
 *
 * @deprecated since it uses XMLScanner
 */
public class XMLParser
extends AStreamIn {
	
	/**Name of the Root Tag of this Tree */
	final static public String STR_ROOT = "Root";
	
	/**Local Reference to the Scanner	 */
	private XMLScanner scan;
	
	/**Current XML Element read */
	//public int currXMLElement;
	
	/** Reference to the current Item 	 */
	protected Object currItem;
	
	/**The Root Element of the Tree generated by this Parser,
	 * also used as Factory to generate the Child Elements,
	 * so you can generate XML Elements or HTML Elements.
	 * Thus it has to be initialized by the Constructors. 	 */
	private XMLElement Root;
	
	/**Depth of the getElement Method,
	 * has to be preserved for iterated Calls  */
	private int Depth = 0;
	
	/**Current Tag, read and initialized on Creation  */
	//private int currTag;
	
	/**Initializing Constructor	 */
	public XMLParser(InputStream IS) throws IOException { this(IS, new XMLElement(STR_ROOT, null)); }
	
	/**Initializing Constructor	 */
	public XMLParser(InputStream IS, XMLElement Root) throws IOException {
		this.Root = Root;
		scan = new XMLScanner(IS);
	}
	
	/**Returns the minimum Number of Items left (in the Buffer).
	 * The actual Number may be higher, so available() should be called again
	 * at the End of this Number. */
	public long availAble() { return (scan.currXMLToken == XMLScanner.XML_TAG_EOF) ? 0 :1; }
	
	/** @see streamIO.object.AStreamIn#getMaxMarkSize()	 */
	public long getMaxMarkSize() { return -1; }
	
	/** @see streamIO.object.AStreamIn#getPosition()	 */
	public long getPosition() { return 0; } //scan.; }
	
	/**Returns the current XML Element	 */
	public Object currItem() { return currItem; }
	
	/**Returns the next XML Element
	 * First Item needs to be loaded and an identified Start Tag (LL(1) Grammar).	 */
	public Object nextItem() {
	    try { return currItem = nextItem(null); 
	    } catch (final IOException e) { 
	    	throw new IllegalStateException(e.toString()); 
	    } 
	}
	
	/**Returns the next XML Element
	 * including all it's subelements as a tree structure.
	 * First Token needs to be read and an identified Start Tag (LL(1) Grammar).	 */
	protected XMLElement nextItem(XMLElement Parent) throws IOException {
	    final String Name = (String) scan.Result;
		if  (	scan.currXMLToken != XMLScanner.XML_TAG_START) throw new AbstractMethodError();
				scan.nextXmlToken(); XMLElement ret = Root.newElement(Name, Parent); //new XMLElement(Name, Parent);
		while(	scan.currXMLToken == XMLScanner.XML_TAG_ATTRIBUTE) {
				KeyValuePair res = (KeyValuePair) scan.Result;
				ret.addAttribute((String) res.key, res); //this is nextList(); duplicate Attributes are still well formed
				scan.nextXmlToken(); }
		while ((scan.currXMLToken == XMLScanner.XML_TAG_TEXT   ) ||
			   (scan.currXMLToken == XMLScanner.XML_TAG_PROCESS) ||
			   (scan.currXMLToken == XMLScanner.XML_TAG_DECLARE) ||
			   (scan.currXMLToken == XMLScanner.XML_TAG_START  )) {
	//		if (scan.currXMLToken == XMLScanner.XML_TAG_DECLARE) ; else //maybe include Code or Callbacks
	//		if (scan.currXMLToken == XMLScanner.XML_TAG_PROCESS) ; else //for Processing later
	//		if (scan.currXMLToken == XMLScanner.XML_TAG_TEXT) ret.addElement(); else //for Processing later
			if (scan.currXMLToken == XMLScanner.XML_TAG_START  )
				ret.addElement((String) scan.Result, nextItem(ret)); else
				ret.addElement("", scan.Result); //anything else is Text Data.
				scan.nextXmlToken(); }
			if (scan.currXMLToken != XMLScanner.XML_TAG_STOP) throw new AbstractMethodError();
			if (!Name.equals(scan.Result)) throw new AbstractMethodError();
		return ret;
	}
	
	/**Finds an XML Element with the given Path Information.
	 * The Path Info is similar to the one given in the graphical JTreeView Component
	 * Either create the whole structure first, but that may be very ineffective,
	 * or do a quick String Search, which may be quite inaccurate and not scalable,
	 * this one parses the structure only until it finds an appropriate Pattern.
	 * The State is cached, so the next occurrence of this Pattern can be searched.
	 * No DOM is created, so memory is saved.
	 * This is well apted to grab the Data wanted from a streamIO.
	 */
	public XMLElement getElement(XMLElement parent, String[] Path) throws IOException {
	    do switch (scan.currXMLToken) {
	               case XMLScanner.XML_TAG_START: if (Path[Depth  ].equals(scan.Result)) ++Depth; break;
	               case XMLScanner.XML_TAG_STOP : if (Path[Depth-1].equals(scan.Result)) --Depth; break;
	               default: //ignore all other Tags.
	    } while ((Depth < Path.length) && //skip reading the next Tag on finding a Start Token!
	            (scan.nextXmlToken() != XMLScanner.XML_TAG_EOF));
	    return nextItem(parent); }
	
	/**tests all Methods of this Class	 */
	public static void testIt() throws IOException {
		StringBufferInputStream IS = new StringBufferInputStream(XMLScanner.tstXML2);
		XMLParser Parser = new XMLParser(IS);
		XMLElement root = null;
	    final String[] Path = {"Icon", "Division", "Name"};//, "", "", };
	    root = Parser.getElement(root, Path);
	    root = Parser.getElement(root, Path);
	    root = Parser.getElement(root, Path);
	    IS = new StringBufferInputStream(XMLScanner.tstXML2);
	    Parser = new XMLParser(IS);
		while (IS.available() > 0) {
			root = (XMLElement) Parser.nextItem();
		    System.out.println(root.toString() ); }
	}
	
}
