
(object Petal
    version    	42
    _written   	"Rose 4.5.8163.3"
    charSet    	0)

(object SubSystem "RingFuncs"
    is_unit    	TRUE
    is_loaded  	TRUE
    quid       	"37BC93CE025B"
    visible_modules 	(list dependency_list
	(object Dependency_Relationship
	    quid       	"37BC93CE0270"
	    supplier   	"Component View::Ring"
	    quidu      	"36BB392A02D1"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC93CE0272"
	    supplier   	"Component View::intFunction"
	    quidu      	"36BB39470388"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC93CE02B1"
	    supplier   	"Component View::Group"
	    quidu      	"36BB25E0024F"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC93CE035C"
	    supplier   	"Component View::BaseCopy"
	    quidu      	"36BABF4B0011"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC93CF0042"
	    supplier   	"Component View::Metric"
	    quidu      	"36BB45940014"
	    supplier_is_subsystem 	TRUE)
	(object Dependency_Relationship
	    quid       	"37BC93CF0103"
	    supplier   	"Component View::GroupM"
	    quidu      	"36BB2CD10088"
	    supplier_is_subsystem 	TRUE))
    physical_models 	(list unit_reference_list
	(object module "f1_xx" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\f1_xx.java"))
	    quid       	"37BC93CE025D"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CE0271"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CE0273"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23300073"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23300074"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1001B6"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1001B7"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fDouble" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fDouble.java"))
	    quid       	"37BC93CE0298"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CE02B2"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CE02B3"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23310117"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23310118"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A110237"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A110238"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fEulerFktn" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fEulerFktn.java"))
	    quid       	"37BC93CE0338"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CE035B"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CE035D"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CE035E"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233203E9"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233203EA"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23330009"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A13011A"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A130122"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A130123"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fEulerSum" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fEulerSum.java"))
	    quid       	"37BC93CF002C"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF0043"
		    supplier   	"Component View::Metric"
		    quidu      	"36BB45940014"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF0044"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF0045"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF0046"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23340337"
		    supplier   	"Component View::Metric"
		    quidu      	"36BB45940014"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD2334033F"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23340340"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23340341"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A150054"
		    supplier   	"Component View::Metric"
		    quidu      	"36BB45940014"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A150055"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A150056"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A15005C"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fGeoSum" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fGeoSum.java"))
	    quid       	"37BC93CF00B8"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF00D3"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF00D4"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF00D5"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233800F6"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233800F7"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23380100"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1602E3"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1602E9"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1602EA"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fInverse" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fInverse.java"))
	    quid       	"37BC93CF00EA"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF0104"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF0105"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233A01D6"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233A01D7"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A17031C"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A17031D"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fNegative" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fNegative.java"))
	    quid       	"37BC93CF0126"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF0135"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF013A"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233C02C9"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233C02CA"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A180355"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A18035A"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fSquare" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fSquare.java"))
	    quid       	"37BC93CF0158"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF016D"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF016E"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233E03D0"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD233E03D1"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A190397"
		    supplier   	"Component View::GroupM"
		    quidu      	"36BB2CD10088"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A190398"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "fTwo" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\fTwo.java"))
	    quid       	"37BC93CF01BD"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF01D1"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF01D2"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23410121"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23410122"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1B0018"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1B0019"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "Function2ODE" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\Function2ODE.java"))
	    quid       	"37BC93CF0235"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF0252"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF0253"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23440092"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23440093"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1C029D"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1C029E"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "IdentityCopy" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\IdentityCopy.java"))
	    quid       	"37BC93CF0285"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF0292"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BC93CF0293"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23450113"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23450114"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1D02EB"
		    supplier   	"Component View::intFunction"
		    quidu      	"36BB39470388"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1D02EC"
		    supplier   	"Component View::BaseCopy"
		    quidu      	"36BABF4B0011"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "OdeConst" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\OdeConst.java"))
	    quid       	"37BC93CF02DF"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF02EE"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD234601A6"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A1F0045"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "OdeExp" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\OdeExp.java"))
	    quid       	"37BC93CF0339"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF0352"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD23470224"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A210154"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "OdeLinear" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\OdeLinear.java"))
	    quid       	"37BC93CF039D"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93CF03B6"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD234802AD"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A290055"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "OdeSquare" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\OdeSquare.java"))
	    quid       	"37BC93D0000F"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BC93D00028"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD2349032F"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A2B013E"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java")
	(object module "OdeHeight2D" "NotAModuleType" "NotAModulePart"
	    attributes 	(list Attribute_Set
		(object Attribute
		    tool       	"Java"
		    name       	"FileName"
		    value      	"D:\\Personal\\Code\\Java\\RingFuncs\\OdeHeight2D.java"))
	    quid       	"37BD3A210230"
	    stereotype 	""
	    visible_modules 	(list dependency_list
		(object Dependency_Relationship
		    quid       	"37BD3A2602F6"
		    supplier   	"Component View::Group"
		    quidu      	"36BB25E0024F"
		    supplier_is_subsystem 	TRUE)
		(object Dependency_Relationship
		    quid       	"37BD3A2602F7"
		    supplier   	"Component View::Ring"
		    quidu      	"36BB392A02D1"
		    supplier_is_subsystem 	TRUE))
	    language   	"Java"))
    physical_presentations 	(list unit_reference_list
	(object Module_Diagram "RingFuncs"
	    quid       	"37BF0B820276"
	    title      	"RingFuncs"
	    zoom       	100
	    max_height 	28350
	    max_width  	21600
	    origin_x   	0
	    origin_y   	0
	    items      	(list diagram_item_list
		(object ModView "Component View::RingFuncs::OdeHeight2D" "NotAModuleType" "NotAModulePart" @1
		    location   	(248, 155)
		    label      	(object ItemLabel
			Parent_View 	@1
			location   	(201, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	174
			label      	"OdeHeight2D")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BD3A210230"
		    width      	314
		    autoResize 	TRUE
		    width      	314
		    height     	162)
		(object ModView "Component View::RingFuncs::OdeSquare" "NotAModuleType" "NotAModulePart" @2
		    location   	(682, 155)
		    label      	(object ItemLabel
			Parent_View 	@2
			location   	(644, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	139
			label      	"OdeSquare")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93D0000F"
		    width      	250
		    autoResize 	TRUE
		    width      	250
		    height     	162)
		(object ModView "Component View::RingFuncs::OdeLinear" "NotAModuleType" "NotAModulePart" @3
		    location   	(1085, 155)
		    label      	(object ItemLabel
			Parent_View 	@3
			location   	(1050, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"OdeLinear")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF039D"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::OdeExp" "NotAModuleType" "NotAModulePart" @4
		    location   	(1457, 155)
		    label      	(object ItemLabel
			Parent_View 	@4
			location   	(1422, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"OdeExp")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF0339"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::OdeConst" "NotAModuleType" "NotAModulePart" @5
		    location   	(1860, 155)
		    label      	(object ItemLabel
			Parent_View 	@5
			location   	(1825, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"OdeConst")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF02DF"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::IdentityCopy" "NotAModuleType" "NotAModulePart" @6
		    location   	(2232, 155)
		    label      	(object ItemLabel
			Parent_View 	@6
			location   	(2197, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"IdentityCopy")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF0285"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::Function2ODE" "NotAModuleType" "NotAModulePart" @7
		    location   	(2635, 155)
		    label      	(object ItemLabel
			Parent_View 	@7
			location   	(2597, 130)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	139
			label      	"Function2ODE")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF0235"
		    width      	250
		    autoResize 	TRUE
		    width      	250
		    height     	162)
		(object ModView "Component View::RingFuncs::fTwo" "NotAModuleType" "NotAModulePart" @8
		    location   	(186, 465)
		    label      	(object ItemLabel
			Parent_View 	@8
			location   	(151, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fTwo")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF01BD"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fSquare" "NotAModuleType" "NotAModulePart" @9
		    location   	(589, 465)
		    label      	(object ItemLabel
			Parent_View 	@9
			location   	(554, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fSquare")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF0158"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fNegative" "NotAModuleType" "NotAModulePart" @10
		    location   	(961, 465)
		    label      	(object ItemLabel
			Parent_View 	@10
			location   	(926, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fNegative")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF0126"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fInverse" "NotAModuleType" "NotAModulePart" @11
		    location   	(1364, 465)
		    label      	(object ItemLabel
			Parent_View 	@11
			location   	(1329, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fInverse")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF00EA"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fGeoSum" "NotAModuleType" "NotAModulePart" @12
		    location   	(1736, 465)
		    label      	(object ItemLabel
			Parent_View 	@12
			location   	(1701, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fGeoSum")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF00B8"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fEulerSum" "NotAModuleType" "NotAModulePart" @13
		    location   	(2108, 465)
		    label      	(object ItemLabel
			Parent_View 	@13
			location   	(2073, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fEulerSum")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CF002C"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fEulerFktn" "NotAModuleType" "NotAModulePart" @14
		    location   	(2511, 465)
		    label      	(object ItemLabel
			Parent_View 	@14
			location   	(2476, 440)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fEulerFktn")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CE0338"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::fDouble" "NotAModuleType" "NotAModulePart" @15
		    location   	(186, 744)
		    label      	(object ItemLabel
			Parent_View 	@15
			location   	(151, 719)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"fDouble")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CE0298"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)
		(object ModView "Component View::RingFuncs::f1_xx" "NotAModuleType" "NotAModulePart" @16
		    location   	(589, 744)
		    label      	(object ItemLabel
			Parent_View 	@16
			location   	(554, 719)
			fill_color 	13434879
			anchor_loc 	3
			nlines     	2
			max_width  	127
			label      	"f1_xx")
		    icon_style 	"Icon"
		    line_color 	3342489
		    fill_color 	13434879
		    quidu      	"37BC93CE025D"
		    width      	228
		    autoResize 	TRUE
		    width      	228
		    height     	162)))))
