/* Generated by Together */

package streamIO.object.filterOut;

import streamIO.AStreamOut;
import streamIO.IIStreamOut;
/**
  * Terminal output that throws a preconfigured exception for every item it receives, converting
  * message processing back into an escalation.
  * <p>
  * Title: TryCatchOut<p>
  * Description:
  * Converts any incoming Message into a RuntimeException/Escalation.
  * Can be used to convert Error Processing (back) into Exceptions/Escalation. 
  * Context Information acquired on the way to the Error is lost.
  *
  * While this is a trivial Task and could easily be incorporated
  * into any of the other Filters, the Separation of Granularity by defining
  * Configuration vs. Programming allows to work on a higher Level.
  *
  * Working with Exceptions or Error Streams is a Decision
  * that can be made only in concrete Implementations.
  * Exceptions are frequently used in Programming, they correspond to Escalations.
  * Error Streams are used in Business Modelling, but it may be tedious
  * to define Error Streams at any Level of Processing.
  *
  * Known SubClasses: <none>
  *
  * @see TryCatchOut for a Node that converts the Exception back into an Error streamIO 
  *
  * Copyright:	Copyright (c) Matthias Heuer<p>
  * Company:	personal<p>
  * Created on	2000-11-26, 01;13;44<p>
  * @author 	Matthias Heuer
  * @version	1.0
  * <!-- docstate
  * pass: 2
  * mtime: 2026-09-05T20:49:24Z
  * digest: 27a4bf9898aaa5a6c5a9a6c1b115876326debc3f6b52ada0838c3e16c75b7dde
  * stale: false
  * tags: [code/stream_filter, code/decorator_pattern]
  * concepts: [Stream Filter (Output)]
  * facets: {layer: utility, status: legacy, complexity: medium}
  * -->
  */
public class ThrowOut 
	extends AStreamOut
{

	/** Reference to the Exception that is to be thrown
	  * when an Error happens */
	protected RuntimeException x;

	/** Initializing Constructor */
	public ThrowOut(final RuntimeException x_) {
		this.x = x_; }

	/** Accepts the Argument, logs it and sends it further down the Chain */
	public IIStreamOut addItem(final Object arg) { throw x; }

}
