/* Generated by Together */

package streamIO.object.filterOut;

import streamIO.AStreamOut;
import streamIO.IIStreamOut;
/**
  * Title: TryCatchOut<p>
  * Description:
  * Converts any incoming Message into a RuntimeException/Escalation.
  * Can be used to convert Error Processing (back) into Exceptions/Escalation. 
  * Context Information acquired on the way to the Error is lost.
  *
  * While this is a trivial Task and could easily be incorporated
  * into any of the other Filters, the Separation of Granularity by defining
  * Configuration vs. Programming allows to work on a higher Level.
  *
  * Working with Exceptions or Error Streams is a Decision
  * that can be made only in concrete Implementations.
  * Exceptions are frequently used in Programming, they correspond to Escalations.
  * Error Streams are used in Business Modelling, but it may be tedious
  * to define Error Streams at any Level of Processing.
  *
  * Known SubClasses: <none>
  *
  * @see TryCatchOut for a Node that converts the Exception back into an Error streamIO 
  *
  * Copyright:	Copyright (c) Matthias Heuer<p>
  * Company:	personal<p>
  * Created on	2000-11-26, 01;13;44<p>
  * @author 	Matthias Heuer
  * @version	1.0
  */
public class ThrowOut 
	extends AStreamOut
{

	/** Reference to the Exception that is to be thrown
	  * when an Error happens */
	protected RuntimeException x;

	/** Initializing Constructor */
	public ThrowOut(final RuntimeException x_) {
		this.x = x_; }

	/** Accepts the Argument, logs it and sends it further down the Chain */
	public IIStreamOut addItem(final Object arg) { throw x; }

}
